// ── ELA SETS 4–6 ──────────────────────────────────────────────────

const P4A = `<b>Passage 1 — Riding the Current</b><br><br>
Tomás had grown up watching his father fish the Río Verde every summer, but he had never paddled it himself — until the day his cousin Beto showed up with two battered kayaks and a challenge.<br><br>
"The lower canyon," Beto said, pointing downstream where the river narrowed and turned green-white with foam. "Fifteen minutes. If you make it without flipping, Grandma's tamales are yours."<br><br>
Tomás studied the water. He had read about reading a river — about looking for the V-shapes of current that pointed downstream like arrows, about avoiding flat water that hid submerged rocks. He saw the first V and aimed his bow toward it.<br><br>
The moment he entered the current, everything became noise and cold spray. A wave hit his paddle sideways, and for one terrifying second the kayak tilted. He dug hard on the left, recovered, and breathed.<br><br>
When he scraped onto the gravel bar fifteen minutes later, Beto was already there, grinning. "You read the river," his cousin said. Tomás nodded, still shaking, but something inside him felt very still — the way a river feels in the flat, quiet place after the rapids, where the water finally knows where it's going.`;

const P4B = `<b>Passage 2 — How Rivers Shape the Land</b><br><br>
Rivers are among the most powerful forces shaping Earth's surface. Over thousands of years, moving water carves valleys, deposits soil, and creates the landscapes where most of the world's civilizations developed.<br><br>
Water always moves toward lower ground, following the pull of gravity. As a river flows downhill, it picks up sediment — tiny particles of sand, silt, and rock — and carries them downstream. The faster the water moves, the larger the material it can carry. Mountain rivers, which move quickly, can roll large boulders. Slower rivers in flat areas carry only fine sand and silt.<br><br>
When a river reaches a flatter area, it slows down and deposits its sediment. This is how river deltas and floodplains form — flat, fertile stretches of land built up by centuries of deposited soil. The Nile River delta in Egypt and the Mississippi delta in the United States are among the most famous examples.<br><br>
V-shaped valleys are carved by fast-moving mountain rivers. The same cutting action that creates rapids also slowly cuts the rock walls deeper and deeper. The Colorado River has cut the Grand Canyon to a depth of over one mile over millions of years.<br><br>
Rivers also interact with people. Communities have always settled near rivers for drinking water, transportation, and fertile farmland. Today, rivers provide nearly 70% of the world's drinking water and power millions of homes through hydroelectric dams.`;

const elaSet4 = [
    { q: P4A + `<br><br><hr><b>Question 1.</b> In paragraph 3, Tomás thinks about "reading a river." Based on the context of the story, what does reading a river mean?`, a: ["Studying a map of the river drawn in a book.", "Looking at the water's surface features to understand where it is safe and fast to paddle.", "Reading a sign posted at the river's edge warning about rapids.", "Watching other kayakers to learn from their mistakes."], c: 1, exp: "The text explains Tomás looks for V-shapes and checks for submerged rocks — he is interpreting the visual clues in the water itself.", tag: "RL.3.4" },
    { q: `<b>Question 2.</b> What is the MAIN conflict Tomás must overcome in this story?`, a: ["Convincing his father to let him paddle the canyon.", "Winning a bet against his cousin Beto for tamales.", "His fear of the fast water and the challenge of paddling the lower canyon safely.", "Finding the right kayak for the river conditions."], c: 2, exp: "The central challenge is Tomás paddling dangerous rapids alone for the first time — everything else (the bet, his cousin) is context. His internal conflict is fear vs. courage.", tag: "RL.3.3" },
    { q: `<b>Question 3.</b> Read the last sentence of Passage 1: <i>"the way a river feels in the flat, quiet place after the rapids, where the water finally knows where it's going."</i><br>What does this simile tell you about how Tomás feels?`, a: ["He is exhausted and wants to stop kayaking.", "He feels calm, settled, and sure of himself after getting through the challenge.", "He wishes the river were longer and more exciting.", "He is still frightened and not sure he survived."], c: 1, exp: "The simile compares Tomás's inner stillness to a calm river after rapids — peaceful, clear, and certain. It shows he feels resolved and confident after his challenge.", tag: "RL.3.4" },
    { q: `<b>Question 4.</b> Which event represents the <b>climax</b> of the story?`, a: ["Beto arrives with two kayaks and issues the challenge.", "Tomás studies the water and identifies the V-shapes.", "The wave hits his paddle sideways and the kayak tilts — he nearly flips.", "Tomás scrapes onto the gravel bar and Beto greets him."], c: 2, exp: "The climax is the moment of highest tension: the kayak tilting, Tomás nearly capsizing, and his decision to dig hard and recover.", tag: "RL.3.5" },
    { q: `<b>Question 5.</b> What does the word <b>"submerged"</b> mean as used in paragraph 3?`, a: ["sharply pointed and sticking upward.", "hidden below the water's surface.", "extremely slippery and smooth.", "moving faster than the current around them."], c: 1, exp: "Context: 'flat water that hid submerged rocks' — hidden beneath the surface. Submerged = underwater.", tag: "RL.3.4" },
    { q: `<b>Question 6.</b> Which theme BEST fits Passage 1?`, a: ["Competition between cousins often ends in friendship.", "Preparation and courage together allow a person to succeed in a difficult challenge.", "Rivers are too dangerous for beginners to paddle.", "Family traditions are the most important part of a person's identity."], c: 1, exp: "Tomás prepares (reads the river, uses what he knows) and acts with courage — both elements combine for his success. This is the central theme.", tag: "RL.3.2" },
    { q: P4B + `<br><br><hr><b>Question 7.</b> According to Passage 2, why can mountain rivers carry boulders but slower rivers carry only sand and silt?`, a: ["Mountain rivers are wider and have more water volume.", "Faster water has more energy and can carry heavier material.", "Mountain rivers are colder and the cold water is stronger.", "Slower rivers flow underground where there are no large rocks."], c: 1, exp: "Passage 2 states: 'The faster the water moves, the larger the material it can carry.' Speed = energy = carrying capacity.", tag: "RI.3.3" },
    { q: `<b>Question 8.</b> According to Passage 2, how are V-shaped valleys formed?`, a: ["By glaciers slowly grinding through mountain rock.", "By fast-moving mountain rivers that cut deeper and deeper into rock over time.", "By rivers depositing silt and sediment in low valleys.", "By volcanic activity pushing rock upward into peaks."], c: 1, exp: "Passage 2: 'V-shaped valleys are carved by fast-moving mountain rivers. The same cutting action that creates rapids also slowly cuts the rock walls deeper.'", tag: "RI.3.1" },
    { q: `<b>Question 9.</b> The word <b>"sediment"</b> in Passage 2 most likely means —`, a: ["large boulders and rocks that block river flow.", "tiny particles of sand, silt, and rock carried by water.", "the foam created when water moves quickly over rocks.", "organisms that live on the river floor."], c: 1, exp: "The passage defines it directly: 'sediment — tiny particles of sand, silt, and rock.'", tag: "RI.3.4" },
    { q: `<b>Question 10.</b> What is the MAIN idea of Passage 2?`, a: ["Rivers provide most of the world's drinking water.", "Rivers are powerful forces that shape Earth's surface, transport sediment, and support human life.", "The Colorado River carved the Grand Canyon over millions of years.", "V-shaped valleys are only found near mountain rivers."], c: 1, exp: "The passage covers how rivers shape land, move sediment, form landforms, AND support civilization — all details support this overarching main idea.", tag: "RI.3.2" },
    { q: `<b>Question 11.</b> Which text feature would BEST help a reader of Passage 2 understand how a V-shaped valley forms?`, a: ["A timeline of when famous rivers were discovered.", "A cross-section diagram showing a river cutting deeper into rock over time.", "A photograph of people swimming in a river.", "A glossary defining the word 'delta.'"], c: 1, exp: "A cross-section diagram shows the cutting process visually, making the abstract geological concept concrete and clear.", tag: "RI.3.5" },
    { q: `<b>Question 12.</b> Which detail from Passage 1 is explained by information in Passage 2?`, a: ["Beto offered tamales as a prize for completing the challenge.", "Tomás looked for V-shapes in the water — and Passage 2 explains that V-shaped formations in rivers indicate the downstream current direction.", "Tomás grew up watching his father fish.", "The kayaks were old and battered."], c: 1, exp: "Passage 1 shows Tomás using V-shapes as navigation tools. Passage 2 explains that rapids and fast current create V-formations — the science behind the paddling technique.", tag: "RL.3.9" },
    { q: `<b>Question 13.</b> How are the <b>purposes</b> of Passage 1 and Passage 2 DIFFERENT?`, a: ["Passage 1 informs readers about river science; Passage 2 entertains readers with a story.", "Passage 1 entertains through a personal adventure narrative; Passage 2 informs by explaining how rivers work and shape the land.", "Both passages have the same purpose — to teach readers to kayak safely.", "Passage 1 is a persuasive essay; Passage 2 is a poem."], c: 1, exp: "Standard genre distinction: narrative fiction (entertain) vs. informational text (inform/explain).", tag: "RI.3.6" },
    { q: `<b>Question 14.</b> According to Passage 2, what percentage of the world's drinking water comes from rivers?`, a: ["About 30%.", "About 50%.", "Nearly 70%.", "More than 90%."], c: 2, exp: "Passage 2 states directly: 'rivers provide nearly 70% of the world's drinking water.'", tag: "RI.3.1" },
    { q: `<b>Question 15.</b> A student is comparing Tomás's story to what Passage 2 teaches. She writes: "Tomás used science to survive the river." Which detail supports this claim?`, a: ["Tomás accepted the challenge from cousin Beto.", "Tomás had watched his father fish the river every summer.", "Tomás used knowledge of V-shaped currents to navigate the rapids — the same flow principle explained in Passage 2.", "Tomás scraped onto the gravel bar at the end of the run."], c: 2, exp: "Using V-shapes (water science) to steer safely is the direct application of river knowledge — it connects Passage 1's story to Passage 2's science.", tag: "RL.3.9" },
    { q: `<b>Question 16.</b> In Passage 1, what does the phrase <b>"the bow"</b> likely refer to?`, a: ["A ribbon tied to the front of the kayak.", "The front end of the kayak.", "A paddle stroke used to turn the boat.", "A weapon Tomás carried on the river."], c: 1, exp: "In watercraft, the 'bow' is the front of the boat. Context: 'He aimed his bow toward it' — aiming the front of the kayak at the V-shape current.", tag: "RL.3.4" },
    { q: `<b>Question 17.</b> Which word BEST describes Tomás's character? Use evidence from the story.`, a: ["Reckless — he entered the rapids without thinking.", "Prepared and courageous — he studied the water before entering and recovered when the kayak tilted.", "Competitive — winning the bet against Beto was his only goal.", "Frightened — he was terrified the entire time and never felt calm."], c: 1, exp: "Tomás reads the river (prepared), enters anyway despite fear (courageous), and recovers from near-capsizing (resilient). Multiple text details support this.", tag: "RL.3.3" },
    { q: `<b>Question 18.</b> What does the word <b>"fertile"</b> mean as used in Passage 2?`, a: ["too wet and muddy for growing crops.", "capable of producing abundant plant growth.", "permanently frozen due to extreme cold.", "rocky and difficult to farm."], c: 1, exp: "Context: 'flat, fertile stretches of land built up by deposited soil' that support farming. Fertile = capable of supporting abundant growth.", tag: "RI.3.4" },
    { q: `<b>Question 19.</b> Which sentence is an <b>opinion</b>?`, a: ["The Colorado River has cut the Grand Canyon to a depth of over one mile.", "Rivers provide nearly 70% of the world's drinking water.", "The Nile River delta is the most important landmass in all of Africa.", "Fast-moving rivers can carry larger material than slow rivers."], c: 2, exp: "'Most important landmass' is a judgment that cannot be measured — it is an opinion. The other three are verifiable facts.", tag: "RI.3.8" },
    { q: `<b>Question 20.</b> Both passages mention the idea of rivers being powerful. Which statement BEST connects both passages on this idea?`, a: ["Both passages say rivers are too dangerous to use without expert training.", "Passage 1 shows personal, immediate power of a river (nearly capsizing Tomás); Passage 2 shows geological power (carving canyons, shaping continents) — together they present rivers as forces on every scale.", "Passage 1 says rivers are calm; Passage 2 says rivers are dangerous.", "Both passages focus only on mountain rivers."], c: 1, exp: "Together, the passages show rivers are powerful at a human scale (P1: nearly flips a kayak) and a geological scale (P2: carves canyons over millions of years). It's a complete picture of river force.", tag: "RI.3.9" },
    { q: `<b>Question 21.</b> What does the phrase <b>"deposits its sediment"</b> mean in Passage 2?`, a: ["Picks up rock and sand as it speeds up.", "Drops and leaves behind the rock, sand, and silt it was carrying.", "Dissolves the sediment into the water.", "Moves the sediment backward upstream."], c: 1, exp: "When a river slows, it loses energy and can no longer carry material — it 'deposits' (drops and leaves behind) the sediment it was transporting.", tag: "RI.3.4" },
    { q: `<b>Question 22.</b> Which structure does Passage 2 PRIMARILY use?`, a: ["Chronological — events happen in time order.", "Cause and effect — reasons explain outcomes in natural processes.", "Problem and solution — a geologic problem is proposed and solved.", "Compare and contrast — two rivers are compared side by side."], c: 1, exp: "The passage uses cause-effect throughout: gravity → rivers flow downhill; speed → carries more sediment; slowing → deposits sediment; cutting → V-valleys form.", tag: "RI.3.8" },
    { q: `<b>Question 23.</b> Write a strong CONCLUDING sentence for a report titled "Rivers: Forces That Shape Our World." Which option is BEST?`, a: ['"Rivers are wet and often cold."', '"I think rivers are very cool and everyone should visit one."', '"From carving canyons to feeding civilizations, rivers are among Earth\'s most essential and powerful forces — always moving, always shaping the world we live in."', '"Rivers have water in them and that water flows downhill."'], c: 2, exp: "A strong conclusion restates the main idea in a memorable way, using specific language and leaving a lasting impression. Option C does this clearly.", tag: "W.3.2" }
];

// ─────────────────────────────────────────────────────────────
const P5A_poem1 = `<b>Poem 1 — First Snow</b><br><br>
The first snow falls on silent feet,<br>
No warning given, no sound to greet —<br>
Just white on the sill when you wake from sleep,<br>
A world gone quiet, soft, and deep.<br><br>
The oak tree wears a coat of lace,<br>
The pond forgets its summer face,<br>
And all the ordinary things<br>
Are given back as offerings.<br><br>
I press my palm against the glass<br>
And watch the slow white hours pass,<br>
Wondering if the snow can know<br>
How much I needed it to snow.`;

const P5A_poem2 = `<b>Poem 2 — August Heat</b><br><br>
August is a heavy curtain drawn<br>
Across the window of the year —<br>
No breeze, no rain, no cooling dawn,<br>
Just heat that makes the world unclear.<br><br>
The sidewalk shimmers like a dream,<br>
The garden droops its dusty head,<br>
And even rivers slow to a gleam,<br>
Running thin, almost half-dead.<br><br>
But sit beneath the willow's shade<br>
And feel the slow green quiet there —<br>
Even August has a softer blade<br>
For those who know the patient art of standing still in burning air.`;

const P5B = `<b>Passage 3 — How Weather Shapes Our Emotions</b><br><br>
Scientists have long studied the relationship between weather and human mood. Research suggests that people's emotional states are influenced — though not controlled — by weather conditions around them.<br><br>
Cold, grey days are often associated with feelings of tiredness and low mood, while bright sunshine tends to increase energy levels and positive feelings. A 2011 study found that people reported higher life satisfaction on days with more sunlight, even when they were not spending time outdoors.<br><br>
Interestingly, rain and storms can have different emotional effects depending on the person. Some individuals find rainy days comforting and use them for creative activities like reading or journaling. Others feel restless or anxious during storms.<br><br>
Snow, in particular, has a powerful psychological effect. The muffling quality of snow — which actually absorbs sound waves — creates a physical silence that many people find calming and almost magical. This effect is well-documented: cities are measurably quieter after a heavy snowfall.<br><br>
Researchers emphasize that weather influences mood, but does not determine it. Factors such as sleep, social connection, physical activity, and personal outlook play much larger roles. Still, paying attention to how weather affects you can be a useful part of understanding your own emotional patterns.`;

const elaSet5 = [
    { q: P5A_poem1 + `<br><br><hr><b>Question 1.</b> In "First Snow," what does "falls on silent feet" mean?`, a: ["The snow makes a crunching sound as it lands.", "The snow arrives quietly, without any warning sound.", "Someone with bare feet is walking in the snow.", "The snow melts before it reaches the ground."], c: 1, exp: "Snow doesn't have feet — this is personification giving snow a human quality (silent walking) to suggest it arrives without any sound or warning.", tag: "RL.3.4" },
    { q: `<b>Question 2.</b> In "First Snow," the line <i>"The oak tree wears a coat of lace"</i> uses what literary device?`, a: ["Simile — compares the tree to lace using 'like' or 'as.'", "Metaphor — describes snow on branches as a lace coat without using 'like' or 'as.'", "Onomatopoeia — the word 'lace' sounds like snow falling.", "Rhyme — 'lace' and 'face' end in the same sound."], c: 1, exp: "The tree IS wearing a lace coat (snow on branches) with no comparison word — this is a direct metaphor. Note: 'lace' and 'face' do rhyme, but the figure of speech in this line is metaphor.", tag: "RL.3.4" },
    { q: `<b>Question 3.</b> What does the last stanza of "First Snow" suggest about the speaker's emotional state?`, a: ["The speaker is annoyed that it snowed and has to shovel.", "The speaker feels a deep need for the peace and beauty the snow brings.", "The speaker is scientifically curious about how snow forms.", "The speaker is worried the snow will damage the oak tree."], c: 1, exp: "'I needed it to snow' — the speaker expresses a deep personal longing. The snow's quiet beauty fulfilled an emotional need.", tag: "RL.3.5" },
    { q: P5A_poem2 + `<br><br><hr><b>Question 4.</b> In "August Heat," the poet writes: <i>"August is a heavy curtain drawn across the window of the year."</i> This is —`, a: ["a simile comparing August to a curtain using 'like.'", "a metaphor comparing August's heavy, blocking feeling to a drawn curtain.", "personification giving August the ability to draw a curtain.", "alliteration repeating the 'h' sound in heavy and heat."], c: 1, exp: "August IS a heavy curtain (direct equation, no 'like/as') = metaphor. It captures the oppressive, blocking feeling of summer heat.", tag: "RL.3.4" },
    { q: `<b>Question 5.</b> What does "The sidewalk shimmers like a dream" describe?`, a: ["The sidewalk has been painted with glitter.", "The heat makes the air above the sidewalk appear to ripple and blur — the way a dream is unclear.", "The sidewalk is covered in ice from frost.", "The speaker is dreaming about going outside."], c: 1, exp: "Hot asphalt causes heat shimmer — light bending through hot air creates a blurry, dreamlike visual effect. The simile captures this perfectly.", tag: "RL.3.4" },
    { q: `<b>Question 6.</b> Compare the <b>mood</b> of "First Snow" and "August Heat." Which statement is MOST accurate?`, a: ["Both poems feel sad and lonely throughout.", "Both poems feel joyful and energetic.", "'First Snow' has a quiet, wondering, peaceful mood; 'August Heat' opens with discomfort but ends with a note of calm patience.", "'First Snow' is angry, while 'August Heat' is joyful."], c: 2, exp: "Snow poem: 'quiet, soft, deep' — peaceful and wondering. Heat poem: 'heavy, unclear, drooping' — then ends with 'patient art of standing still.' Contrast but both find stillness.", tag: "RL.3.5" },
    { q: `<b>Question 7.</b> Both poems address extreme weather. What do the <b>speakers of both poems</b> share?`, a: ["Both are angry at the weather and want it to change.", "Both observe weather closely and find meaning or emotion in it, even when it is uncomfortable.", "Both speakers are children building snowmen.", "Both speakers are scientists studying weather patterns."], c: 1, exp: "Both poets watch their weather carefully (pressing hand to glass; sitting under willow) and draw emotional or philosophical meaning from it.", tag: "RL.3.9" },
    { q: P5B + `<br><br><hr><b>Question 8.</b> According to Passage 3, what is one effect that bright sunshine tends to have on people?`, a: ["It makes people feel tired and want to sleep more.", "It increases energy levels and positive feelings.", "It causes people to spend more time indoors.", "It makes people feel anxious and restless."], c: 1, exp: "Passage 3 states: 'bright sunshine tends to increase energy levels and positive feelings.'", tag: "RI.3.1" },
    { q: `<b>Question 9.</b> Why does snow create a "physical silence" according to Passage 3?`, a: ["Snow is cold, and cold temperatures freeze sound waves.", "Snow covers all roads so no vehicles drive.", "Snow absorbs sound waves, making cities measurably quieter.", "People stay indoors during snowstorms."], c: 2, exp: "Passage 3 explains: 'The muffling quality of snow — which actually absorbs sound waves — creates a physical silence.'", tag: "RI.3.3" },
    { q: `<b>Question 10.</b> What is the MAIN idea of Passage 3?`, a: ["Bad weather always makes people feel sad.", "Snow is the most powerful weather event for human emotions.", "Weather influences — but does not control — human emotions, and understanding this can help people know themselves better.", "Sunlight is the only weather condition that affects mood positively."], c: 2, exp: "The passage makes clear weather influences (not controls) mood, and multiple weather types are discussed. The conclusion is about self-understanding through noticing patterns.", tag: "RI.3.2" },
    { q: `<b>Question 11.</b> Which word from Passage 3 means "capable of being measured and proven"?`, a: ["Influenced", "Psychological", "Measurably", "Comforting"], c: 2, exp: "'Cities are measurably quieter' — measurably means it can be detected and proven through measurement (a tool, data). The -ly suffix signals it describes the degree of something provable.", tag: "RI.3.4" },
    { q: `<b>Question 12.</b> According to Passage 3, which factor does NOT primarily determine mood?`, a: ["Sleep quality.", "Social connection.", "Physical activity.", "How hot or cold the weather is."], c: 3, exp: "The passage states: 'Factors such as sleep, social connection, physical activity, and personal outlook play MUCH LARGER roles' than weather. Weather influences, not determines.", tag: "RI.3.1" },
    { q: `<b>Question 13.</b> How does "First Snow" connect to the information in Passage 3?`, a: ["The poem describes the scientific process of how snow absorbs sound.", "The speaker's feeling of deeply needing the snow illustrates how snow's silencing, calming quality can fulfill an emotional need — exactly what Passage 3 explains.", "The poem disagrees with Passage 3 by saying snow is frightening.", "The poem is set in a city that becomes quieter after snowfall, just as Passage 3 describes for all cities."], c: 1, exp: "In the poem, the speaker needed the snow — its peace filled an emotional need. Passage 3 explains snow uniquely calms through physical silence. The poem is a personal example of this effect.", tag: "RL.3.9" },
    { q: `<b>Question 14.</b> In "August Heat," the poet writes that the garden "droops its dusty head." What literary device is this?`, a: ["Simile — the garden is compared to something drooping.", "Metaphor — the heat is described as a curtain.", "Personification — the garden is given a human action (drooping a head).", "Onomatopoeia — 'droops' sounds like what it describes."], c: 2, exp: "Gardens don't have heads — but here the garden 'droops its dusty head' like a tired person. That is personification (giving a plant a human quality).", tag: "RL.3.4" },
    { q: `<b>Question 15.</b> The author of Passage 3 says weather "influences — though not controls." Why does the author include this clarification?`, a: ["To show that weather is not very important to human feelings.", "To be accurate: weather shapes our mood but our choices and other factors ultimately determine our emotional state.", "To argue that scientists don't understand weather very well.", "To tell readers to ignore the weather when making decisions."], c: 1, exp: "The dash and phrase 'though not controls' is a careful correction — the author is being precise about what the research shows: influence, not determination.", tag: "RI.3.6" },
    { q: `<b>Question 16.</b> "First Snow" ends: <i>"Wondering if the snow can know / How much I needed it to snow."</i><br>What does the speaker wonder?`, a: ["Whether snow can be scientifically proven to affect emotion.", "Whether the snow, in a poetic sense, could sense or understand how deeply the speaker longed for its quietness and beauty.", "Whether there will be more snowfall later in the week.", "Whether the snow will melt before morning."], c: 1, exp: "The speaker personifies snow — wondering if it could 'know' (be aware of) the emotional need it fulfilled. It's a poetic, wondering question about connection between person and nature.", tag: "RL.3.5" },
    { q: `<b>Question 17.</b> Both poems use <b>stanzas</b>. How many stanzas does "August Heat" have?`, a: ["2", "3", "4", "5"], c: 1, exp: "'August Heat' has 3 stanzas (groups of lines separated by blank lines): lines 1-4, lines 5-8, and lines 9-12.", tag: "RL.3.5" },
    { q: `<b>Question 18.</b> Which of the following BEST describes the <b>author's purpose</b> in Passage 3?`, a: ["To entertain readers with stories about how storms affect characters in a novel.", "To inform readers about scientific research on the relationship between weather and human emotion.", "To persuade readers to move somewhere with better weather.", "To describe the author's personal emotional reaction to rain."], c: 1, exp: "Passage 3 presents scientific research, studies, and findings in a neutral, informative tone — it is written to inform, not entertain or persuade.", tag: "RI.3.6" },
    { q: `<b>Question 19.</b> A friend says: "August Heat is a depressing poem because it's just about being too hot." Which detail BEST argues AGAINST this reading?`, a: ["The poem mentions drooping gardens and slow rivers.", "The poem's final lines offer a solution — sitting in shade and practicing patient stillness — suggesting calm can be found even in heat.", "The poem rhymes its lines consistently throughout.", "The poem compares August to a heavy curtain."], c: 1, exp: "The ending 'patient art of standing still in burning air' is a moment of wisdom, not despair — it finds a path to calm within discomfort, contradicting a purely depressing reading.", tag: "RL.3.5" },
    { q: `<b>Question 20.</b> Which text structure does Passage 3 PRIMARILY use?`, a: ["Chronological — the passage describes events in order of when they happened.", "Cause and effect — research findings explain causes of mood changes and their effects.", "Compare and contrast — two scientific studies are compared side by side.", "Problem and solution — a weather problem is presented and a cure is offered."], c: 1, exp: "Passage 3 describes causes (weather types) and their effects on mood (sadness, energy, calm). Classic cause-effect structure.", tag: "RI.3.8" },
    { q: `<b>Question 21.</b> Which of the following is MOST likely an opinion?`, a: ['"A 2011 study found that people reported higher life satisfaction on days with more sunlight."', '"Snow absorbs sound waves."', '"First Snow is the most beautifully written poem about winter in American literature."', '"Cities are measurably quieter after a heavy snowfall."'], c: 2, exp: "'Most beautifully written' is a personal aesthetic judgment — it cannot be measured. The others are research findings or physical facts.", tag: "RI.3.8" },
    { q: `<b>Question 22.</b> All three texts in this unit (both poems + the informational passage) explore the idea of weather and human response. Which statement BEST unites what all three teach?`, a: ["People should always stay indoors when the weather is extreme.", "The weather we experience shapes our inner emotional world in ways that are both personal and scientifically real.", "Scientists understand more about weather than poets do.", "August and January are the most important months to study."], c: 1, exp: "The two poems show personal, emotional responses to weather; Passage 3 confirms this is real and scientifically supported. Together they confirm weather and emotion are deeply linked.", tag: "RL.3.9" },
    { q: `<b>Question 23.</b> A student is writing an essay titled "Why Weather Matters to More Than Just Farmers." Which pair of details from the texts provides the STRONGEST evidence?`, a: ["The oak tree wears snow / August has dusty gardens.", "Passage 3: sunlight increases positive feelings / 'First Snow's' speaker needed the snow for emotional reasons.", "Passage 3: rivers provide drinking water / August Heat mentions slow rivers.", "The two poems both rhyme / Passage 3 was written in 2011."], c: 1, exp: "The research finding (Passage 3) plus the poem's emotional 'need' best support why weather matters emotionally to all people, not just for food/farming.", tag: "RI.3.9" }
];

// ─────────────────────────────────────────────────────────────
const P6A = `<b>Passage 1 — The Cartographer's Daughter</b><br><br>
Mira's mother made maps. Not digital ones with satellites — hand-drawn maps on wide paper, with hatched mountains and tiny trees and rivers shown as wavering blue lines. Her studio smelled of ink and coffee, and rolls of unfinished continents leaned against every wall.<br><br>
One afternoon, Mira brought home a failing grade on a geography test and set it on the drawing table without a word. Her mother studied the red marks without expression, then slid a blank sheet of paper across the table.<br><br>
"Draw what you know," she said.<br><br>
"I don't know anything," Mira said. "That's why I failed."<br><br>
Her mother turned back to her work. "You know your route to school. Draw that."<br><br>
Mira drew the street, then the corner with the bakery, then the park where the shortcut went through, then the hill where you could see the church steeple two streets over. Twenty minutes later she had covered the page.<br><br>
"Now look," her mother said. "You already make maps. You just didn't know that's what they were called."<br><br>
The next day, Mira studied geography by drawing — every country a story, every border a line she understood because she had learned to understand lines. She passed the next test. But more than that, she stopped thinking of the world as something to memorize and started thinking of it as something to explore.`;

const P6B = `<b>Passage 2 — Maps Through Human History</b><br><br>
Humans have been making maps for at least 14,000 years. The earliest known map is a clay tablet from ancient Babylon that shows a river, mountains, and a city — all depicted with simple symbols. Even before writing was invented, people drew maps to share information about the world.<br><br>
Maps have always served multiple purposes. Navigation maps help travelers find their way. Topographic maps show the shape of the land, including hills, valleys, and rivers. Political maps show country borders. Weather maps track storms. Medical maps can show where diseases are spreading. Each type of map asks: what information matters, and how can it be shown clearly?<br><br>
The invention of the printing press in the 1440s transformed mapmaking. Before printing, maps had to be copied by hand, which meant errors crept in. After printing, identical copies could be produced quickly — but some early printed maps still contained errors inherited from ancient sources, including a sea monster placed in the North Atlantic where cartographers had simply written: <i>Here be dragons.</i><br><br>
Today, digital mapping tools like GPS and satellite imagery have made navigation easier than ever. But cartographers — professional mapmakers — still exist. They design maps for scientific research, urban planning, environmental protection, and education, where hand-drawn or specially designed maps communicate things that digital tools miss.<br><br>
Maps are more than directions. They are arguments about what matters, what is central, and how the world should be understood.`;

const elaSet6 = [
    { q: P6A + `<br><br><hr><b>Question 1.</b> Why does Mira's mother say "Draw what you know" instead of telling Mira to study harder?`, a: ["She wants Mira to take art class instead of geography.", "She understands that Mira already has spatial knowledge and wants her to build confidence from what she can do, not from what she thinks she cannot do.", "She is too busy working on her maps to give Mira direct advice.", "She wants to make Mira feel bad about her grade."], c: 1, exp: "The mother's strategy is to show Mira she already knows how to think spatially — she draws from life experience. It's teaching through discovery rather than lecturing.", tag: "RL.3.3" },
    { q: `<b>Question 2.</b> What does the phrase <b>"every country a story"</b> mean in the last paragraph of Passage 1?`, a: ["Mira memorized a story about each country to help her remember it.", "Mira learned to connect each place to something personal and meaningful, so geography became something to discover rather than recite.", "Every country in Mira's textbook had a paragraph of background information.", "Mira wrote fiction stories set in other countries."], c: 1, exp: "The phrase captures how Mira's relationship with geography transformed — places became connected to understanding and meaning, not just memorization.", tag: "RL.3.4" },
    { q: `<b>Question 3.</b> What is the CENTRAL conflict in Passage 1?`, a: ["Mira's mother is too busy with her work to help Mira.", "Mira struggles with geography because she seems to learn differently from how it is traditionally taught.", "Mira disagrees with her mother about what makes a good map.", "Mira's teacher gave her an unfair grade on the test."], c: 1, exp: "Mira failed because traditional memorization didn't work for her. The conflict is her struggle with geography — and the resolution is finding her own learning method.", tag: "RL.3.3" },
    { q: `<b>Question 4.</b> The last sentence of Passage 1 states Mira "stopped thinking of the world as something to memorize and started thinking of it as something to explore." What does this change represent?`, a: ["A change in score — from failing to passing.", "A deeper change in mindset: from passive memorization to active curiosity and engagement with learning.", "A decision to become a professional cartographer like her mother.", "A realization that geography tests are not important."], c: 1, exp: "The shift from 'memorize' to 'explore' signals a transformation in how Mira approaches knowledge itself — a core theme of the story.", tag: "RL.3.2" },
    { q: `<b>Question 5.</b> The description of the mother's studio — "smelled of ink and coffee," "rolls of unfinished continents leaned against every wall" — is an example of —`, a: ["the rising action, where the main conflict builds.", "vivid descriptive detail that establishes the setting and shows the mother's world is thoroughly immersed in mapmaking.", "a metaphor comparing the studio to a geography classroom.", "the narrator explaining the plot to help readers understand the story."], c: 1, exp: "Sensory detail (smell of ink, rolled maps) builds a clear, vivid sense of place and character — this is descriptive writing serving the function of setting.", tag: "RL.3.5" },
    { q: `<b>Question 6.</b> Which theme BEST fits Passage 1?`, a: ["Parents should always do their children's homework for them.", "The best learning happens when we connect new knowledge to what we already understand from experience.", "Geography is the most important school subject.", "Hand-drawn maps are better than digital maps."], c: 1, exp: "Mira learns geography by connecting it to personal experience (her route to school). The story's theme is experiential, connected learning.", tag: "RL.3.2" },
    { q: `<b>Question 7.</b> How is the mother in Passage 1 characterized? Use TWO details from the text.`, a: ["As strict and impatient — she ignores Mira's feelings.", "As patient and wise — she doesn't lecture, just guides, and trusts the process of discovery.", "As distracted and uninvolved — she never looks at Mira's grade.", "As emotional and disappointed — she studies the grade with sadness."], c: 1, exp: "She 'studied the red marks without expression' (calm, not reactive) and 'slid a blank sheet across' without a big speech — she guided quietly and trusted the outcome.", tag: "RL.3.3" },
    { q: P6B + `<br><br><hr><b>Question 8.</b> According to Passage 2, what is the EARLIEST known map?`, a: ["A satellite image from a telescope in space.", "A hand-drawn map of Mira's school route.", "A clay tablet from ancient Babylon showing a river, mountains, and a city.", "A printed map from the 1440s using symbols for mountains."], c: 2, exp: "Passage 2 states: 'The earliest known map is a clay tablet from ancient Babylon that shows a river, mountains, and a city.'", tag: "RI.3.1" },
    { q: `<b>Question 9.</b> What problem with maps was SOLVED by the invention of the printing press?`, a: ["Maps could not show mountains before printing was invented.", "Maps had to be copied by hand, which introduced errors. Printing allowed identical, faster copies.", "Mapmakers could not share their maps with people in other countries.", "Early maps did not include city names or borders."], c: 1, exp: "Passage 2: 'Before printing, maps had to be copied by hand, which meant errors crept in. After printing, identical copies could be produced quickly.'", tag: "RI.3.3" },
    { q: `<b>Question 10.</b> What is the author's purpose in ending Passage 2 with: <i>"Maps are more than directions. They are arguments about what matters, what is central, and how the world should be understood"</i>?`, a: ["To tell readers that maps are often wrong and should not be trusted.", "To leave the reader with a thought-provoking idea — that every map reflects choices about importance and perspective.", "To argue that digital maps are better than hand-drawn ones.", "To summarize the history of map-making in a final sentence."], c: 1, exp: "This final line reframes maps as perspective and argument — a broader, philosophical conclusion that invites the reader to think differently about an everyday tool.", tag: "RI.3.6" },
    { q: `<b>Question 11.</b> According to Passage 2, what is a <b>topographic map</b>?`, a: ["A map that shows country borders and political divisions.", "A map that shows the shape of the land, including hills, valleys, and rivers.", "A map that tracks the movement of storms.", "A map used only by ancient civilizations."], c: 1, exp: "Passage 2 directly defines it: 'Topographic maps show the shape of the land, including hills, valleys, and rivers.'", tag: "RI.3.1" },
    { q: `<b>Question 12.</b> The phrase <b>"Here be dragons"</b> in Passage 2 was used by early cartographers to indicate —`, a: ["areas where sea monsters had been officially seen and recorded.", "unknown or unexplored areas where they had no information to show.", "areas known to be extremely dangerous for all travelers.", "regions where mythical creatures were worshipped."], c: 1, exp: "The passage implies 'Here be dragons' filled spaces cartographers knew nothing about — it was a placeholder for the unknown, not a literal claim about monsters.", tag: "RI.3.4" },
    { q: `<b>Question 13.</b> According to Passage 2, why do professional cartographers still exist even though GPS and satellites are widely available?`, a: ["Because GPS systems frequently break down and need manual backup.", "Because cartographers design specialized maps for research, planning, and education that communicate what digital tools miss.", "Because most people prefer paper maps to digital ones.", "Because the government requires hand-drawn maps by law."], c: 1, exp: "Passage 2: 'cartographers still exist...for scientific research, urban planning, environmental protection, and education, where hand-drawn or specially designed maps communicate things that digital tools miss.'", tag: "RI.3.1" },
    { q: `<b>Question 14.</b> Both passages center on the work of mapmakers (cartographers). How do they present this topic in <b>different ways</b>?`, a: ["Passage 1 is about ancient maps; Passage 2 is about modern maps.", "Passage 1 explores mapmaking as a personal metaphor for understanding the world and learning; Passage 2 examines the factual history and types of maps.", "Both passages are informational texts about the invention of maps.", "Passage 1 argues maps are art; Passage 2 argues maps are science."], c: 1, exp: "Passage 1 = fictional narrative using mapmaking to explore learning and perspective. Passage 2 = informational text presenting history, types, and purpose of maps.", tag: "RL.3.9" },
    { q: `<b>Question 15.</b> The last line of Passage 2 says maps are "arguments about what matters, what is central." How does this CONNECT to Mira's story in Passage 1?`, a: ["Mira argues with her mother about what should go on a map.", "Mira's personal map of her route reflects what she knows and values — showing that even an ordinary map is a choice about what matters, just as Passage 2 describes.", "Mira's mother makes maps that include political borders and sea monsters.", "Mira's school map appears in Passage 2 as an example."], c: 1, exp: "Mira draws what she knows: the bakery, shortcut, steeple — these reflect her values and knowledge. It's a personal 'argument' about what's important, mirroring Passage 2's idea.", tag: "RL.3.9" },
    { q: `<b>Question 16.</b> What does the word <b>"cartographer"</b> most likely mean in both passages?`, a: ["A scientist who studies the Earth's core.", "A professional mapmaker.", "A person who teaches geography in school.", "An artist who paints landscapes."], c: 1, exp: "Context from both passages — Mira's mother 'made maps' (P1) and Passage 2 describes 'cartographers — professional mapmakers' explicitly.", tag: "RI.3.4" },
    { q: `<b>Question 17.</b> Which detail from Passage 2 BEST supports the idea in Passage 1 that maps can teach us how we already understand the world?`, a: ['"The earliest known map is a clay tablet from ancient Babylon."', '"Even before writing was invented, people drew maps to share information about the world."', '"Digital mapping tools like GPS and satellite imagery have made navigation easier."', '"Early printed maps still contained errors inherited from ancient sources."'], c: 1, exp: "People drew maps before writing existed — showing that spatial mapping is a natural human way of organizing and sharing knowledge. This supports how Mira's drawing shows she already 'maps' the world.", tag: "RI.3.9" },
    { q: `<b>Question 18.</b> What text structure does Passage 2 PRIMARILY use?`, a: ["Narrative — it tells a story in order of events.", "Chronological with embedded explanation — it moves through the history of maps while explaining how and why they changed.", "Problem and solution — it presents a mapping problem and offers a solution.", "Compare and contrast — it compares two types of maps side by side."], c: 1, exp: "Passage 2 moves through time (ancient clay tablet → printing press 1440s → today) while explaining developments — mostly chronological with cause-effect embedded.", tag: "RI.3.8" },
    { q: `<b>Question 19.</b> A student wants to find out what type of map would show where mountain ranges are located in South America. Based on Passage 2, which type of map should she use?`, a: ["A political map.", "A weather map.", "A topographic map.", "A medical map."], c: 2, exp: "Passage 2 defines topographic maps as showing 'the shape of the land, including hills, valleys, and rivers' — mountain ranges are topographic features.", tag: "RI.3.5" },
    { q: `<b>Question 20.</b> Which conclusion would BOTH passages support?`, a: ["Geography is the most difficult subject in school.", "Understanding maps — whether personal or global — is a way of making sense of and engaging with the world around us.", "All maps today are made by computers and satellites.", "Learning geography requires memorizing large amounts of facts."], c: 1, exp: "Passage 1 shows maps as personal understanding of the world; Passage 2 says maps are 'how the world should be understood.' Both support maps as tools for making sense of the world.", tag: "RL.3.9" },
    { q: `<b>Question 21.</b> In Passage 1, what does the word <b>"hatched"</b> most likely mean in the phrase "hatched mountains"?`, a: ["Dotted with small squares of color.", "Drawn with short parallel lines to suggest texture and elevation.", "Cut away using a special tool.", "Painted with bright colors to stand out."], c: 1, exp: "Hatching is an artistic technique using short parallel lines to create texture or suggest elevation on hand-drawn maps. The context 'hand-drawn maps…hatched mountains' supports this.", tag: "RL.3.4" },
    { q: `<b>Question 22.</b> Which sentence is an <b>opinion</b>?`, a: ['"Humans have been making maps for at least 14,000 years."', '"The invention of the printing press transformed mapmaking."', '"Hand-drawn maps by professional cartographers are far better than anything a GPS can produce."', '"Today, digital mapping tools like GPS and satellite imagery have made navigation easier."'], c: 2, exp: "'Far better than anything a GPS can produce' is a comparative judgment — a personal opinion. The others are factual or well-supported claims.", tag: "RI.3.8" },
    { q: `<b>Question 23.</b> All six ELA units in this course have featured characters or people who changed how they understood something by engaging with it differently. Which BEST states the overarching theme shared across ALL passages?`, a: ["Tests and grades are the best way to measure what a student has learned.", "The most powerful learning happens when people connect, explore, and actively engage with the world — not just receive or memorize information.", "Every person should study geology, cartography, and ocean science.", "Stories and facts are always in conflict with each other."], c: 1, exp: "Across all units: lighthouses understood through action (S1), observation as active seeing (S2), patient effort (S3), river science lived (S4), weather felt emotionally (S5), geography mapped personally (S6) — all celebrate active, connected learning.", tag: "RL.3.9" }
];
