// ── ELA SETS 1–3 ──────────────────────────────────────────────────

const P1A = `<b>Passage 1 — The Storm Keeper</b><br><br>
Maya had lived near the lighthouse her whole life, but she had never been inside — not until the night old Mr. Calloway called for help. The storm had swept in faster than anyone expected, knocking the backup power out before the main generator could start. Without the beacon, ships in the harbor would have no warning about the rocks below.<br><br>
She climbed the spiral stairs two at a time, her flashlight throwing shadows against the curved stone walls. At the top, Mr. Calloway was working with shaking hands on a panel of switches. "Hold this," he said, pressing a heavy lantern into her arms. "Don't let it tip."<br><br>
Outside, the wind screamed and rain pelted the glass. Maya could see nothing but darkness and white foam far below. Then, slowly, the great light above them coughed to life, sweeping its beam out across the black water.<br><br>
"There," Mr. Calloway said, sinking into his chair with a long breath. "They'll know where the rocks are now."<br><br>
Maya lowered the lantern and looked out at the beam cutting through the storm. She thought of every ship out there turning, reading the light, finding safety. For the first time, she understood what the lighthouse really was — not just a tower on a cliff, but a voice in the dark.`;

const P1B = `<b>Passage 2 — How Lighthouses Work</b><br><br>
Lighthouses are tall towers built near coastlines, harbors, or on rocky islands to warn sailors about dangerous areas. For hundreds of years, before radar or GPS, a lighthouse beam was often the only way a ship's captain knew where the shore was at night or in a storm.<br><br>
The light inside a lighthouse is made powerful by a special set of lenses called a Fresnel (FRAY-nel) lens. These lenses are shaped like a beehive and bend light outward so that the beam can be seen from up to 20 miles away. Each lighthouse also has its own pattern — some flash once every four seconds, others every ten — so sailors can identify exactly which lighthouse they are seeing on a nautical chart.<br><br>
Today, most lighthouses in the United States are automated, meaning no keeper lives there full-time. Sensors detect when it is dark and automatically switch the light on. However, lighthouse keepers were once extremely important. They maintained the lens, kept the fuel burning, and recorded weather conditions in a logbook every single day.<br><br>
Though technology has changed how ships navigate, lighthouses remain an important backup system. During power outages or equipment failures, the lighthouse beam can still guide vessels safely to shore.`;

const elaSet1 = [
    // ── Passage 1 questions (1–11) ──
    { q: P1A + `<br><br><hr><b>Question 1.</b> Read the sentence: <i>"She thought of every ship out there turning, reading the light, finding safety."</i><br>What does the phrase <b>"reading the light"</b> most likely mean?`, a: ["The sailors were holding books near the light.", "The sailors were using the lighthouse beam to understand where the danger was.", "The sailors were learning how to build a lighthouse.", "The sailors were trying to repair the lighthouse."], c: 1, exp: "In context, sailors 'read' a lighthouse beam the way you read a sign — it tells them where the rocks are. The phrase uses figurative language for navigating by the signal.", tag: "RL.3.4" },
    { q: `Reread <b>Passage 1 — The Storm Keeper</b>.<br><br><b>Question 2.</b> Why does Mr. Calloway ask Maya to hold the lantern?`, a: ["He wants her to light the way down the stairs.", "He needs both hands free to work on the switches.", "He is too tired to carry anything heavy.", "He wants to test whether Maya is brave enough."], c: 1, exp: "The text says he 'pressed a heavy lantern into her arms' right before returning to the panel of switches — so he needed his hands free.", tag: "RL.3.1" },
    { q: `<b>Question 3.</b> Which sentence from Passage 1 best supports the idea that the situation was <b>urgent</b>?`, a: ['"Maya had lived near the lighthouse her whole life, but she had never been inside."', '"She climbed the spiral stairs two at a time, her flashlight throwing shadows against the curved stone walls."', '"At the top, Mr. Calloway was working with shaking hands on a panel of switches."', '"Then, slowly, the great light above them coughed to life."'], c: 2, exp: "'Shaking hands' shows physical signs of stress and urgency in Mr. Calloway. It is the strongest evidence that there was real danger.", tag: "RL.3.1" },
    { q: `<b>Question 4.</b> Read the last paragraph of Passage 1: <i>"not just a tower on a cliff, but a voice in the dark."</i><br>This is an example of —`, a: ["simile, because it compares two things using 'like' or 'as'.", "personification, because it gives a lighthouse a human quality (a voice).", "onomatopoeia, because it imitates the sound of the storm.", "alliteration, because it repeats the same beginning sound."], c: 1, exp: "Calling the lighthouse 'a voice in the dark' gives it a human quality — the ability to speak and be heard. That is personification.", tag: "RL.3.4" },
    { q: `<b>Question 5.</b> What is the <b>theme</b> of Passage 1?`, a: ["Old buildings are dangerous and should be repaired.", "Storms are unpredictable and people should stay indoors.", "Even an ordinary person can help others by being willing to act in a difficult moment.", "Lighthouses are more important than modern technology."], c: 2, exp: "Maya, an ordinary girl, takes action during a crisis and helps save ships. The story celebrates courage and helpfulness in unexpected people.", tag: "RL.3.2" },
    { q: `<b>Question 6.</b> How does Maya's feeling about the lighthouse <b>change</b> from the beginning to the end of the story?`, a: ["She goes from excited to bored.", "She goes from curious to frightened.", "She goes from unfamiliar with its importance to deeply understanding what it means.", "She goes from confident to unsure of herself."], c: 2, exp: "At the start Maya had 'never been inside.' By the end she understood the lighthouse was 'a voice in the dark' — a major shift in understanding.", tag: "RL.3.3" },
    { q: `<b>Question 7.</b> What point of view is used in Passage 1?`, a: ["First person — the narrator is Maya and uses 'I.'", "Second person — the narrator speaks directly to the reader using 'you.'", "Third person — the narrator is outside the story and refers to Maya as 'she.'", "Third person omniscient — the narrator tells the thoughts of all characters."], c: 2, exp: "The story uses 'she climbed,' 'she thought' — showing a narrator outside the action who follows Maya's perspective. That is third person.", tag: "RL.3.6" },
    { q: `<b>Question 8.</b> The word <b>"beacon"</b> is used in paragraph 1 of Passage 1. Based on context, beacon most likely means —`, a: ["a loud alarm that warns people with sound.", "a guiding light used as a signal or warning.", "a type of fuel used to power generators.", "a chart that sailors use to read maps."], c: 1, exp: "The text says the beacon provides 'warning about the rocks below' — a guiding warning signal, which matches the definition of 'beacon.'", tag: "RL.3.4" },
    // ── Passage 2 questions (9–16) ──
    { q: P1B + `<br><br><hr><b>Question 9.</b> According to Passage 2, what is the <b>main purpose</b> of a lighthouse?`, a: ["To help lighthouse keepers record the weather each day.", "To warn sailors about dangerous areas near the coast.", "To show sailors how to build a Fresnel lens.", "To replace radar and GPS systems on modern ships."], c: 1, exp: "The passage states lighthouses 'warn sailors about dangerous areas' in the opening paragraph.", tag: "RI.3.2" },
    { q: `<b>Question 10.</b> According to Passage 2, why does each lighthouse have its own <b>flash pattern</b>?`, a: ["So that the light is bright enough to be seen from 20 miles away.", "So that sailors can identify which specific lighthouse they are seeing.", "So that the automated sensors know when to turn the light on.", "So that the keeper can tell how long the light has been running."], c: 1, exp: "The passage directly states each pattern is unique 'so sailors can identify exactly which lighthouse they are seeing on a nautical chart.'", tag: "RI.3.1" },
    { q: `<b>Question 11.</b> How does the <b>Fresnel lens</b> help the lighthouse beam travel farther?`, a: ["It makes the light flash faster so it is noticed more easily.", "It is shaped to bend light outward, making the beam visible from up to 20 miles away.", "It uses electricity instead of fuel so the light is stronger.", "It records weather conditions that might block the light."], c: 1, exp: "The passage says the Fresnel lens is 'shaped like a beehive and bends light outward so that the beam can be seen from up to 20 miles away.'", tag: "RI.3.3" },
    { q: `<b>Question 12.</b> What does the word <b>"automated"</b> mean as used in Passage 2?`, a: ["kept running by a human worker at all times.", "Operated by machines or sensors without a person present.", "broken down and in need of repair.", "lit only during storms and emergencies."], c: 1, exp: "The passage explains automated lighthouses have 'no keeper living there full-time' and sensors switch the light on automatically — automated means machine-operated.", tag: "RI.3.4" },
    { q: `<b>Question 13.</b> Which text structure does Passage 2 mainly use?`, a: ["Chronological order — events are told in time order.", "Problem and solution — a problem is presented and then answered.", "Cause and effect — reasons are given for outcomes.", "Description/explanation — the author explains what something is and how it works."], c: 3, exp: "Passage 2 describes what lighthouses are, how the lens works, and how they are operated — it is primarily explanatory/descriptive in structure.", tag: "RI.3.8" },
    { q: `<b>Question 14.</b> Which detail from Passage 2 shows that lighthouse keepers had an <b>important and demanding</b> job?`, a: ['"Today, most lighthouses in the United States are automated."', '"Each lighthouse also has its own pattern."', '"They maintained the lens, kept the fuel burning, and recorded weather conditions in a logbook every single day."', '"Lighthouses remain an important backup system."'], c: 2, exp: "Maintaining the lens, tending fuel, and logging weather 'every single day' shows the job was constant and critical.", tag: "RI.3.8" },
    // ── Cross-passage (15–18) ──
    { q: `<b>Question 15.</b> Both passages discuss lighthouses. Which statement best describes how the two passages are <b>DIFFERENT</b>?`, a: ["Passage 1 explains the science of the Fresnel lens while Passage 2 tells a story about a storm.", "Passage 1 is a fictional narrative about one night in a lighthouse; Passage 2 is an informational text explaining how lighthouses work.", "Passage 1 is a poem about the ocean; Passage 2 is a newspaper article.", "Both passages tell the same story in different ways."], c: 1, exp: "Passage 1 is fiction/narrative; Passage 2 is informational/explanatory. They present the same subject in very different formats.", tag: "RI.3.9" },
    { q: `<b>Question 16.</b> Mr. Calloway in Passage 1 is described as working with "shaking hands." Based on Passage 2, which detail BEST explains WHY his job in that moment was so critical?`, a: ["Lighthouse keepers must record weather conditions every day.", "Without the lighthouse beam, ships at sea could not identify the rocks and might crash.", "The Fresnel lens can be seen from 20 miles away.", "Most lighthouses in the U.S. are now automated."], c: 1, exp: "Passage 2 explains lighthouses 'warn sailors about dangerous areas.' Without the beam, ships would not know where the rocks were — making Mr. Calloway's work life-or-death.", tag: "RI.3.9" },
    { q: `<b>Question 17.</b> How does Passage 1 help you <b>understand</b> the last paragraph of Passage 2, which says: "During power outages or equipment failures, the lighthouse beam can still guide vessels safely to shore"?`, a: ["Passage 1 shows that lighthouses can only be operated by professional lighthouse keepers.", "Passage 1 shows a power outage happening at a lighthouse and a person manually restoring the light to save ships — a real example of that backup role.", "Passage 1 explains how the Fresnel lens works during an outage.", "Passage 1 describes the history of automated lighthouses."], c: 1, exp: "The story in Passage 1 IS an example of a power outage — backup is restored by hand, saving ships. It brings Passage 2's factual claim to life.", tag: "RL.3.9" },
    { q: `<b>Question 18.</b> A student is writing a report titled "Why Lighthouses Still Matter Today." Which source would be MOST useful?`, a: ["A fictional adventure novel about a sailor lost at sea.", "An encyclopedia article about the history and function of lighthouses.", "A poem about ocean waves and storms.", "A personal diary written by a lighthouse keeper in 1890."], c: 1, exp: "An encyclopedia article provides factual, organized information about both history and function — best for a research report.", tag: "RI.3.5" },
    { q: `<b>Question 19.</b> Which sentence is an <b>OPINION</b>, not a fact?`, a: ['"Each lighthouse has its own flash pattern."', '"Lighthouses are the most beautiful structures ever built on the American coast."', '"The Fresnel lens can be seen from up to 20 miles away."', '"Lighthouse keepers recorded weather conditions in a logbook."'], c: 1, exp: "'Most beautiful structures ever built' is a personal judgment — it cannot be measured or proven. The others are observable facts.", tag: "RI.3.8" },
    { q: `<b>Question 20.</b> Choose the BEST summary of Passage 2.`, a: ["Lighthouse keepers had very hard jobs and should be remembered.", "Lighthouses use a powerful Fresnel lens and unique flash patterns to warn sailors of danger. Though mostly automated today, they remain a crucial backup navigation system.", "The Fresnel lens was invented many years ago and is shaped like a beehive.", "GPS has made lighthouses unnecessary, but some still operate for historical reasons."], c: 1, exp: "The best summary covers the main ideas: how lighthouses work (lens, patterns), their history (keepers), and their present role (automated, backup). Option B does this.", tag: "RI.3.2" },
    { q: `<b>Question 21.</b> Which graphic feature would BEST help a reader of Passage 2 understand how the Fresnel lens bends light?`, a: ["A timeline showing when each U.S. lighthouse was built.", "A labeled diagram showing the lens shape and how the beam spreads outward.", "A map of all lighthouses along the East Coast.", "A photo of a lighthouse keeper working in 1900."], c: 1, exp: "The passage describes how the lens is shaped and how it bends light — a labeled diagram would show this visually and clearly.", tag: "RI.3.5" },
    { q: `<b>Question 22.</b> In Passage 1, the author writes that the lighthouse engine "coughed to life." This is an example of —`, a: ["simile — comparing the engine to a person using 'like.'", "onomatopoeia — a word that sounds like what it describes.", "personification — giving the machine a human action (coughing).", "hyperbole — an extreme exaggeration."], c: 2, exp: "Machines do not 'cough' — that is a human action. Applying a human action to a non-human thing is personification.", tag: "RL.3.4" },
    { q: `<b>Question 23.</b> A student argues: "The lighthouse in Passage 1 is just a building — it has no real importance." Which TWO pieces of evidence from BOTH passages best argue AGAINST this claim?<br>(Choose the answer that includes the two strongest pieces of evidence.)`, a: ["Passage 1: Maya held a lantern. / Passage 2: Lighthouses use fuel.", "Passage 1: Ships could see the beam and find safety. / Passage 2: Without the beacon, ships risk crashing on rocks.", "Passage 1: Mr. Calloway had shaking hands. / Passage 2: The lens is shaped like a beehive.", "Passage 1: The stairs are made of curved stone. / Passage 2: Keepers recorded the weather."], c: 1, exp: "The most powerful counterevidence is the life-saving function: ships use the beam to find safety (P1) and without it they risk crashing (P2 logic). Both directly refute the claim.", tag: "RL.3.9" }
];

// ─────────────────────────────────────────────────────────────
const P2A = `<b>Passage 1 — A Letter from Camp</b><br><br>
<i>July 14th</i><br><br>
Dear Grandma,<br><br>
I know you thought I would love camp right away, but I have to be honest: the first three days were terrible. My bunkmate Priscilla snores so loudly I can barely sleep, the food is nothing like yours, and on the second day I fell into the lake during the canoe lesson. (Everyone laughed. I did not.)<br><br>
By day four, though, something started to change. Our counselor, Ms. Rivera, saw me sitting by myself after dinner and sat down next to me. She didn't say anything at first, which I thought was odd. Then she pointed to the fireflies starting to blink in the meadow and said, "Most people miss those." I hadn't even noticed them.<br><br>
Since then, I've been paying attention to things I normally rush past. Yesterday I found a spider web covered in dew that looked like a string of tiny pearls. This morning a heron flew over the lake so low I could hear its wings.<br><br>
I still miss home. But I think Ms. Rivera was teaching me something that day — not about fireflies, but about slowing down.<br><br>
Love,<br>
Cora`;

const P2B = `<b>Passage 2 — The Science of Noticing: How Observation Skills Help Us Learn</b><br><br>
Scientists, doctors, artists, and detectives all share one powerful skill: careful observation. Observation means more than simply looking — it means paying close, purposeful attention to details that other people might overlook.<br><br>
When children practice observation, researchers have found they become better problem-solvers and more creative thinkers. This is because close attention to the world trains the brain to notice patterns, ask questions, and make connections between things that seem unrelated.<br><br>
Simple habits can build this skill. Keeping a nature journal — where you record what you see, hear, smell, and feel outdoors — is one of the most effective methods. Drawing what you observe, even poorly, forces your eyes to slow down and actually look. Scientists call this "slow seeing."<br><br>
Some schools now include structured outdoor observation time in their curriculum. Students who participated in these programs scored higher on science reasoning tests and reported feeling calmer and more focused in class.<br><br>
Observation is not a talent people are born with. It is a skill that grows with practice, just like reading or playing a musical instrument. The more intentionally you look, the more the world reveals.`;

const elaSet2 = [
    { q: P2A + `<br><br><hr><b>Question 1.</b> Cora describes her first three days at camp as "terrible." Which detail from the letter does <b>NOT</b> support that description?`, a: ["Her bunkmate snores and keeps her awake.", "She fell into the lake and people laughed at her.", "Ms. Rivera sat next to her without speaking at first.", "The food does not taste like her grandmother's cooking."], c: 2, exp: "Ms. Rivera sitting beside Cora happens on day four and marks a positive turning point — it does not support the 'terrible' description.", tag: "RL.3.1" },
    { q: `<b>Question 2.</b> What lesson does Cora say Ms. Rivera was teaching her?`, a: ["How to find fireflies after dark.", "How to feel less homesick at camp.", "How to slow down and pay purposeful attention to the world.", "How to make friends with people who are different from you."], c: 2, exp: "Cora ends the letter saying Ms. Rivera was teaching her 'not about fireflies, but about slowing down.' This is the stated lesson.", tag: "RL.3.2" },
    { q: `<b>Question 3.</b> Read this sentence from the letter: <i>"I found a spider web covered in dew that looked like a string of tiny pearls."</i><br>This is an example of —`, a: ["metaphor, because it states the dew drops ARE tiny pearls.", "simile, because it says the dew drops LOOKED LIKE tiny pearls.", "personification, because it gives the spider web a human quality.", "onomatopoeia, because 'pearls' sounds like the thing it names."], c: 1, exp: "The comparison uses 'looked like' — the signal word for a simile.", tag: "RL.3.4" },
    { q: `<b>Question 4.</b> How does Cora's <b>mood</b> change from the beginning to the end of the letter?`, a: ["She goes from happy to sad.", "She goes from miserable and lonely to more observant and quietly hopeful.", "She goes from bored to excited about canoeing.", "She goes from angry at Ms. Rivera to grateful for the camp."], c: 1, exp: "The letter moves from 'the first three days were terrible' to finding beauty in spider webs and herons — a clear emotional shift toward openness and reflection.", tag: "RL.3.3" },
    { q: `<b>Question 5.</b> What is the <b>most likely reason</b> the author wrote this letter in a first-person point of view?`, a: ["To give scientific facts about fireflies and herons.", "To persuade the reader to go to summer camp.", "To share a personal experience in an honest, immediate way that helps readers connect with Cora's feelings.", "To compare two different letters written by campers."], c: 2, exp: "First-person letters feel personal and honest. We hear Cora's real thoughts and emotions, creating a direct connection.", tag: "RL.3.6" },
    { q: `<b>Question 6.</b> What does the word <b>"odd"</b> mean as Cora uses it: "which I thought was odd"?`, a: ["unkind and rude.", "strange or unexpected.", "very smart and clever.", "quiet and peaceful."], c: 1, exp: "Cora expected Ms. Rivera to say something — the silence struck her as strange or unusual. 'Odd' means 'not what one would expect.'", tag: "RL.3.4" },
    { q: `<b>Question 7.</b> Which phrase from the letter is an example of <b>hyperbole</b> (an exaggeration)?`, a: ['"I found a spider web covered in dew."', '"Most people miss those."', '"Priscilla snores so loudly I can barely sleep."', '"A heron flew over the lake so low I could hear its wings."'], c: 2, exp: "Saying she 'can barely sleep' because of snoring is a common humorous exaggeration (hyperbole) — not a literal scientific fact.", tag: "RL.3.4" },
    { q: P2B + `<br><br><hr><b>Question 8.</b> According to Passage 2, what does <b>"slow seeing"</b> mean?`, a: ["Looking at things that move very slowly, like snails or clouds.", "Drawing or recording observations to force your eyes to truly look at details.", "A type of vision problem that makes seeing difficult.", "Watching a video in slow motion to study science."], c: 1, exp: "The passage says drawing 'forces your eyes to slow down and actually look — scientists call this slow seeing.' It is a deliberate way to observe carefully.", tag: "RI.3.4" },
    { q: `<b>Question 9.</b> Which claim from Passage 2 is supported by <b>research evidence</b>?`, a: ["Observation is more important than reading.", "Drawing poorly is better than drawing well.", "Children who practice observation become better problem-solvers and more creative thinkers.", "Every child should keep a nature journal every day."], c: 2, exp: "The passage says 'researchers have found' that children who practice observation become better problem-solvers — direct research support.", tag: "RI.3.8" },
    { q: `<b>Question 10.</b> What is the <b>main idea</b> of Passage 2?`, a: ["Doctors and detectives are skilled at observation.", "Keeping a nature journal is the only way to improve observation skills.", "Observation is a learnable skill that improves thinking and can be developed through intentional practice.", "Schools that require outdoor time get better test scores."], c: 2, exp: "The passage introduces observation as a shared skill among experts, explains its benefits, gives methods, and concludes it grows with practice — the main idea is that it's a learnable, valuable skill.", tag: "RI.3.2" },
    { q: `<b>Question 11.</b> Which text feature would BEST help a reader locate the part of Passage 2 that explains <b>how to build observation skills</b>?`, a: ["A numbered list of every word in the passage.", "A bold subheading such as 'How to Practice Observation.'", "A picture of a scientist in a laboratory.", "A glossary defining the word 'observation.'"], c: 1, exp: "A bold subheading would directly guide the reader to that section of the text.", tag: "RI.3.5" },
    { q: `<b>Question 12.</b> According to Passage 2, students in structured outdoor observation programs —`, a: ["were more likely to become professional scientists.", "scored higher on science reasoning tests and felt calmer in class.", "stopped doing as well in reading and math.", "spent too much time outdoors and fell behind in school."], c: 1, exp: "The passage states these students 'scored higher on science reasoning tests and reported feeling calmer and more focused in class.'", tag: "RI.3.1" },
    { q: `<b>Question 13.</b> What does the last sentence of Passage 2 mean: <i>"The more intentionally you look, the more the world reveals"</i>?`, a: ["If you wear glasses, you will see more than people who don't.", "As your observation skills grow, you will notice more details around you.", "The world is full of secrets that only scientists can find.", "Looking at a screen is better than looking at nature."], c: 1, exp: "The sentence means purposeful attention rewards you with more discoveries — the world 'gives' you more when you look carefully.", tag: "RI.3.4" },
    { q: `<b>Question 14.</b> A student says: "Both passages argue that slowing down and paying attention has value." Which detail from EACH passage best supports that claim?<br>(Choose the pair that gives the strongest support from both passages.)`, a: ["Passage 1: Cora fell in the lake. / Passage 2: Scientists study things.", "Passage 1: Ms. Rivera pointed to fireflies Cora had not noticed. / Passage 2: 'Slow seeing' — drawing to force your eyes to look carefully.", "Passage 1: The food was not like Grandma's. / Passage 2: Schools give outdoor time to students.", "Passage 1: Priscilla snores at night. / Passage 2: Observation is more important than reading."], c: 1, exp: "Ms. Rivera teaches Cora to notice what she 'normally rushed past' (P1), directly paralleling 'slow seeing' in P2 — both illustrate the reward of slowing down.", tag: "RI.3.9" },
    { q: `<b>Question 15.</b> How do Passage 1 and Passage 2 <b>approach the same idea differently</b>?`, a: ["Passage 1 uses scientific data; Passage 2 uses a personal story.", "Passage 1 shows the idea through one girl's personal experience in a letter; Passage 2 explains the idea using research and examples.", "Passage 1 is about summer; Passage 2 is about winter.", "Both passages use fictional stories to teach the same lesson."], c: 1, exp: "Passage 1 is a personal narrative/letter; Passage 2 is an informational article with research. Both address observation, but from very different angles.", tag: "RL.3.9" },
    { q: `<b>Question 16.</b> The word <b>"intentionally"</b> in the last line of Passage 2 means —`, a: ["accidentally or by chance.", "on purpose, with focused effort.", "quickly and efficiently.", "nervously or with worry."], c: 1, exp: "'Intentionally' means doing something deliberately — on purpose with effort. Context: 'the more intentionally you look' = the more focused your attention.", tag: "L.3.4" },
    { q: `<b>Question 17.</b> Which sentence BEST states the <b>theme</b> found in BOTH passages?`, a: ["Camp is a good place to make friends and try new things.", "Paying careful attention to small things can change how you see the world.", "Scientific skills are the most important skills a person can learn.", "Nature journals are a fun hobby for children and adults."], c: 1, exp: "Cora's letter shows attention transforming her experience. Passage 2 argues attention expands perception. Both support the theme of paying careful attention.", tag: "RL.3.9" },
    { q: `<b>Question 18.</b> Read this sentence from Passage 2: <i>"It is a skill that grows with practice, just like reading or playing a musical instrument."</i><br>What type of figurative language is this?`, a: ["Metaphor", "Simile", "Personification", "Hyperbole"], c: 1, exp: "The comparison uses 'just like' — the signal word for a simile.", tag: "RI.3.4" },
    { q: `<b>Question 19.</b> A student wants to write a report comparing how Cora's experience in Passage 1 shows what Passage 2 explains about observation. Which would be the BEST way to organize that report?`, a: ["Write only about Cora's feelings with no reference to the science.", "Introduce observation skills (from Passage 2), then connect each of Cora's discoveries to a specific skill or effect described in Passage 2.", "Summarize each passage in a separate paragraph with no connections made between them.", "Retell Cora's letter in different words."], c: 1, exp: "Good analytical writing introduces the topic, then builds evidence with specific connections between the texts.", tag: "W.3.2" },
    { q: `<b>Question 20.</b> According to Passage 2, which of the following is <b>NOT</b> stated as a benefit of practicing observation?`, a: ["Students become better problem-solvers.", "Students become more creative thinkers.", "Students feel calmer and more focused.", "Students perform better in mathematics than in any other subject."], c: 3, exp: "The passage does not say observation specifically improves mathematics performance. The specific claims are: problem-solving, creativity, science reasoning, and calmness.", tag: "RI.3.1" },
    { q: `<b>Question 21.</b> What does the phrase <b>"pays purposeful attention"</b> mean in Passage 2?`, a: ["Gives money in exchange for a lesson.", "Focuses intently and deliberately on specific details.", "Pays a teacher to explain how to look at things.", "Attends school on time every day."], c: 1, exp: "'Purposeful attention' means directed, deliberate focus — looking with clear intent at specific details.", tag: "RI.3.4" },
    { q: `<b>Question 22.</b> Which detail from Passage 1 is the BEST example of what Passage 2 calls "slow seeing"?`, a: ["Cora mentions that the food is not like her grandmother's.", "Cora notices a spider web covered in dew that looks like a string of tiny pearls.", "Cora says her bunkmate snores at night.", "Cora fell into the lake during canoe practice."], c: 1, exp: "'Slow seeing' in Passage 2 means genuinely observing fine details. Noticing the dew on the spider web's pearls-like quality is exactly that deliberate, detailed looking.", tag: "RL.3.9" },
    { q: `<b>Question 23.</b> The author of Passage 2 includes the detail about students scoring higher on science reasoning tests in order to —`, a: ["prove that all schools should cancel outdoor time.", "entertain readers with an interesting story about students.", "provide factual evidence that supports the claim that observation skills have measurable benefits.", "compare two different types of schools."], c: 2, exp: "Authors include data to support claims. The test score detail provides measurable proof that observation skills produce real academic benefits.", tag: "RI.3.6" }
];

// ─────────────────────────────────────────────────────────────
const P3A = `<b>Passage 1 — The Stonecutter's Wish</b><br><br>
<i>(A Japanese folk tale)</i><br><br>
Long ago, a stonecutter named Tasaku spent his days carving great blocks of rock from the mountainside. One afternoon, a wealthy merchant passed by in a golden palanquin carried by four servants, and Tasaku thought, "How powerful that man is! I wish I were a merchant."<br><br>
A spirit who lived in the mountain heard his wish and granted it. Tasaku became a merchant and dressed in fine silks. But soon the summer sun beat down so fiercely that even his fine canopy gave no shade, and he thought, "The sun is more powerful than any merchant. I wish I were the sun."<br><br>
The spirit granted the wish. As the sun, Tasaku burned crops and dried rivers, and he felt very powerful. Then a great cloud drifted across the sky and blocked his rays. "A cloud is more powerful than the sun," he thought. "I wish I were a cloud."<br><br>
As a cloud, he poured rain on the land. But then a mighty wind pushed him across the sky like a leaf. "The wind is stronger than a cloud! I wish I were the wind."<br><br>
As the wind, he bent trees double and tossed ships at sea. But when he came to the great mountain, he could not move it so much as an inch. "The mountain is the most powerful of all," he decided. "I wish I were the mountain."<br><br>
And so he became the mountain — until he heard a small, steady hammering at his base. A stonecutter was chipping away at his rock, and Tasaku could do nothing to stop him.<br><br>
"Ah," he thought. "A patient, skilled worker is stronger than any mountain." And he asked to become a stonecutter again.`;

const P3B = `<b>Passage 2 — Granite: How Mountains Are Made</b><br><br>
Mountains may look permanent, but they are always changing — just very, very slowly. Most mountains are formed in one of three ways: by the collision of huge plates of Earth's crust, by volcanic activity, or by erosion that carves away softer rock and leaves harder rock standing tall.<br><br>
The most common rock found in mountains is granite. Granite forms deep underground, where heat and pressure cause minerals to melt together and slowly cool into a very hard crystalline rock. It can take millions of years for granite to rise to the surface as the land above erodes away.<br><br>
Once a mountain is exposed, erosion begins working on it immediately. Rain, ice, wind, and even living things like tree roots slowly break the rock apart. Glaciers — huge, slow-moving sheets of ice — are especially powerful. As a glacier moves, it carries rocks inside it that grind against the mountain like sandpaper.<br><br>
The same process that breaks mountains down also creates soil. Tiny pieces of rock, mixed with decayed plant material, form the rich soil that plants need to grow. In this way, the mountain feeds the valley below even as it is slowly worn away.<br><br>
Stone-cutting, the craft Tasaku the character practices, works on the same principle as natural erosion: applying steady force repeatedly to a hard surface causes gradual but permanent change.`;

const elaSet3 = [
    { q: P3A + `<br><br><hr><b>Question 1.</b> Which statement BEST describes the pattern in Tasaku's wishes?`, a: ["He wishes for the same thing each time until the spirit stops listening.", "Each time he gains power, he realizes there is something more powerful, and so he wishes for that instead.", "He wishes for wealth first, then for wisdom, and finally for peace.", "He keeps wishing to return to his old life until finally he does."], c: 1, exp: "The pattern is a chain: merchant → sun → cloud → wind → mountain. Each wish comes from noticing something stronger than what he currently is.", tag: "RL.3.3" },
    { q: `<b>Question 2.</b> What is the <b>moral</b> (lesson) of this folk tale?`, a: ["The sun is the most powerful force in nature.", "Wealth and fine clothes lead to happiness.", "True power comes not from status or size, but from steady, skilled effort.", "It is wrong to wish for things you do not have."], c: 2, exp: "A small stonecutter's repeated effort defeats the mighty mountain — showing that persistent, skilled work is ultimately more powerful than grand status.", tag: "RL.3.2" },
    { q: `<b>Question 3.</b> When Tasaku says "A patient, skilled worker is stronger than any mountain," this is an example of —`, a: ["the climax, where the main character solves the problem.", "the exposition, where characters and setting are introduced.", "the resolution, where the character's lesson is stated and the story ends.", "the rising action, where the character faces new challenges."], c: 2, exp: "Tasaku's realization and return to being a stonecutter ends the story — it is the resolution, the final stage of plot structure.", tag: "RL.3.5" },
    { q: `<b>Question 4.</b> Why is this story classified as a <b>folk tale</b> rather than realistic fiction?`, a: ["It is set in Japan, which is a real country.", "It features a magical spirit who grants wishes, which could not happen in real life.", "It has a character who works as a stonecutter.", "It teaches a moral lesson about patience."], c: 1, exp: "Realistic fiction must follow the rules of the real world. A wish-granting spirit who transforms a man into the sun is fantasy/magic — a hallmark of folk tales.", tag: "RL.3.5" },
    { q: `<b>Question 5.</b> The word <b>"palanquin"</b> is used in paragraph 1. Based on context clues, a palanquin is most likely —`, a: ["a large, brightly decorated shop.", "an enclosed seat or platform carried by servants.", "a type of expensive silk cloth.", "a musical instrument played at celebrations."], c: 1, exp: "The text says it was 'carried by four servants' — so it is something people ride in that requires carriers: an enclosed seat or litter.", tag: "RL.3.4" },
    { q: `<b>Question 6.</b> Which sentence from the story is the BEST example of <b>irony</b> — where the outcome is the opposite of what a character expected?`, a: ['"As the sun, Tasaku burned crops and dried rivers."', '"The spirit who lived in the mountain heard his wish and granted it."', '"He became the mountain — until he heard a small, steady hammering at his base."', '"As the wind, he bent trees double and tossed ships at sea."'], c: 2, exp: "Tasaku wished for the greatest power (the mountain) but was then helpless against a single small stonecutter — the very thing he was before. This is the central irony.", tag: "RL.3.4" },
    { q: `<b>Question 7.</b> Which word BEST describes Tasaku at the beginning of the story?`, a: ["Content and grateful.", "Discontented and always wanting something more.", "Patient and hardworking.", "Generous and kind."], c: 1, exp: "Tasaku sees the merchant and immediately wants to be him — not satisfied with his own life. Throughout the story he is never content until the end.", tag: "RL.3.3" },
    { q: P3B + `<br><br><hr><b>Question 8.</b> According to Passage 2, what are the <b>three main ways</b> mountains form?`, a: ["Erosion, glacier movement, and rainfall.", "Collision of Earth's plates, volcanic activity, and erosion.", "Granite cooling, wind shaping, and stonecutting.", "Heat, pressure, and plant root growth."], c: 1, exp: "Passage 2 lists exactly these three: 'collision of huge plates of Earth's crust, volcanic activity, or erosion that carves away softer rock.'", tag: "RI.3.1" },
    { q: `<b>Question 9.</b> According to Passage 2, why is granite so <b>hard</b>?`, a: ["It is formed from volcanic lava cooling quickly on the Earth's surface.", "It contains tree roots that bind it together.", "It forms deep underground where heat and pressure cause minerals to melt and slowly cool into a crystalline rock.", "It is made of ice that was compressed over millions of years."], c: 2, exp: "Passage 2 explains granite's hardness comes from minerals melting together 'and slowly cool into a very hard crystalline rock' under deep pressure and heat.", tag: "RI.3.3" },
    { q: `<b>Question 10.</b> The last paragraph of Passage 2 says stonecutting "works on the same principle as natural erosion." What principle are both based on?`, a: ["Applying heat and water to soften rock.", "Using large machines to move mountains quickly.", "Applying steady force repeatedly to a hard surface causes gradual but permanent change.", "Mixing rock with plants to create soil."], c: 2, exp: "The passage states directly: 'applying steady force repeatedly to a hard surface causes gradual but permanent change' — this describes both erosion and stonecutting.", tag: "RI.3.3" },
    { q: `<b>Question 11.</b> In Passage 2, the author compares a glacier to —`, a: ["a river that carves canyon walls smoothly.", "sandpaper, grinding against the mountain as it moves.", "a loud hammering tool used by workers.", "an enormous wind that pushes rock aside."], c: 1, exp: "The passage says a glacier 'carries rocks inside it that grind against the mountain like sandpaper.'", tag: "RI.3.4" },
    { q: `<b>Question 12.</b> What does the word <b>"erosion"</b> most likely mean, based on how it is used in Passage 2?`, a: ["The slow building up of rock layers over time.", "The process by which rock and soil are gradually broken down and carried away.", "The heat inside the Earth that melts minerals together.", "A type of earthquake that splits mountains apart."], c: 1, exp: "Context clues: erosion 'carves away softer rock,' rain and ice 'break rock apart,' glaciers 'grind against the mountain' — all describe wearing away, not building up.", tag: "RI.3.4" },
    { q: `<b>Question 13.</b> According to Passage 2, how does a mountain eventually <b>help create soil</b>?`, a: ["The mountain melts and flows into valleys as liquid rock.", "The heat inside mountains bakes soil in surrounding areas.", "Tiny rock pieces mixed with decayed plant material form rich soil.", "Glaciers deposit soil from other regions as they melt."], c: 2, exp: "Passage 2 states: 'Tiny pieces of rock, mixed with decayed plant material, form the rich soil that plants need to grow.'", tag: "RI.3.1" },
    { q: `<b>Question 14.</b> The author of Passage 2 ends with a paragraph linking the folk tale character Tasaku to real geology. What is the author's purpose in doing this?`, a: ["To show that folk tales are always scientifically accurate.", "To connect the informational content back to the folk tale and show that the story's central idea — repeated effort changes rock — has a real scientific basis.", "To argue that stonecutters are more important than scientists.", "To explain why folk tales should be taught in science class."], c: 1, exp: "The closing paragraph bridges fiction and fact, showing Tasaku's trade reflects a true geological principle — purposefully tying both passages together.", tag: "RI.3.6" },
    { q: `<b>Question 15.</b> Both passages deal with the power to change mountains. How do the two passages present this idea <b>differently</b>?`, a: ["Passage 1 says mountains can never be changed; Passage 2 says they can.", "Passage 1 uses a fictional story to show that patient human effort can overcome even a mountain; Passage 2 explains scientifically how nature erodes mountains over time.", "Passage 1 explains the geology of mountain formation; Passage 2 tells a fictional story.", "Both passages say that only wind can erode a mountain."], c: 1, exp: "Passage 1 = fiction/folk tale about human will; Passage 2 = informational text about natural processes. Both address changing mountains, through very different lenses.", tag: "RL.3.9" },
    { q: `<b>Question 16.</b> Which detail from Passage 2 BEST supports the moral of Passage 1?`, a: ['"Granite forms deep underground where heat and pressure cause minerals to melt."', '"Most mountains are formed in one of three ways."', '"Even granite, one of the hardest rocks, is slowly broken down by the steady, repeated action of rain, ice, and glaciers over millions of years."', '"Stone-cutting works on the same principle as natural erosion: steady force causes gradual but permanent change."'], c: 3, exp: "The explicit connection in the last paragraph — steady force = permanent change — directly mirrors and validates the folk tale's lesson about patient effort.", tag: "RI.3.9" },
    { q: `<b>Question 17.</b> Which choice best describes the <b>text structure</b> of Passage 2?`, a: ["Chronological narrative — events are told in the order they happened.", "Problem and solution — a problem is introduced and a solution is given.", "Cause and effect — the passage explains why and how geological processes happen.", "Compare and contrast — two types of mountains are compared."], c: 2, exp: "Passage 2 explains causes (pressure, heat, glaciers) and their effects (mountains form, granite hardens, erosion occurs, soil is created) — classic cause-effect structure.", tag: "RI.3.8" },
    { q: `<b>Question 18.</b> A student wants to find out how long it takes granite to form. Which would be the BEST resource?`, a: ["The folk tale from Passage 1.", "A geology textbook or encyclopedia article about rock formation.", "A dictionary definition of 'granite.'", "A map showing where granite mountains are found in the United States."], c: 1, exp: "A geology textbook provides detailed, accurate scientific information about formation timescales — the best source for that specific fact.", tag: "RI.3.5" },
    { q: `<b>Question 19.</b> Reread: <i>"Mountains may look permanent, but they are always changing — just very, very slowly."</i><br>What is the author's purpose in starting the passage this way?`, a: ["To scare readers with how quickly mountains can disappear.", "To correct a common misunderstanding — that mountains appear unchanging but are in fact always being shaped.", "To inform readers that all mountains will be gone in 100 years.", "To make readers want to climb mountains before they disappear."], c: 1, exp: "The opening directly challenges the assumption that mountains are permanent — it sets up the passage's main argument about gradual, ongoing change.", tag: "RI.3.6" },
    { q: `<b>Question 20.</b> Which statement from Passage 1 shows that Tasaku has <b>learned his lesson</b>?`, a: ['"How powerful that man is! I wish I were a merchant."', '"The mountain is the most powerful of all."', '"A patient, skilled worker is stronger than any mountain."', '"As the wind, he bent trees double and tossed ships at sea."'], c: 2, exp: "Only the third option shows Tasaku's final realization — that humble, skillful effort surpasses all grand power. This is the lesson.", tag: "RL.3.2" },
    { q: `<b>Question 21.</b> The word <b>"crystalline"</b> in Passage 2 most likely means —`, a: ["made of liquid that flows when heated.", "having a clear, organized structure formed from cooled minerals.", "extremely fragile and easily broken.", "relating to the color and appearance of crystal clear water."], c: 1, exp: "Context: minerals 'melt together and slowly cool into a very hard crystalline rock.' Crystalline describes the organized, solid, mineral-based structure that results from cooling.", tag: "RI.3.4" },
    { q: `<b>Question 22.</b> A student writes: <i>"Tasaku was foolish to keep making wishes."</i> Is this a fact or an opinion? Explain which answer is BEST.`, a: ["It is a fact because the story says he made many wishes.", "It is an opinion because 'foolish' is a judgment — other readers might see his wishes as natural human curiosity.", "It is a fact because folk tales always teach us that wishing is wrong.", "It is an opinion because the author of the story never wrote it down."], c: 1, exp: "'Foolish' is a judgment word — a value evaluation. It cannot be proven true or false by looking at the text. That makes it an opinion.", tag: "RI.3.8" },
    { q: `<b>Question 23.</b> Which BEST states what BOTH passages teach the reader?`, a: ["Mountains are difficult to understand without scientific equipment.", "Persistent, repeated effort — whether by nature or people — can overcome even the hardest challenges.", "Folk tales from Japan are always related to geology.", "Wishes never come true in real life."], c: 1, exp: "Both texts center on this idea: steady repeated effort (stonecutting/erosion) eventually overcomes the hardest obstacle (the mountain).", tag: "RL.3.9" }
];
