// NJSLA Grade 3 ELA – 6 sets × 23 questions + Chinese 3 sets × 5 questions
const elaDB = {
    set1: [
        { q: "READ: 'The oak tree stood for 100 years, shading every family who lived in the house.' Main idea?", a: ["Tree needs water", "Tree is old and important to the home", "Family planted it", "Branches were long"], c: 1, exp: "Age and role for families = main idea.", tag: "RI.3.2" },
        { q: "Best evidence for that main idea?", a: ["'stood tall'", "'100 years'", "'shading every family'", "'the house'"], c: 2, exp: "Shading every family shows its importance across generations.", tag: "RI.3.8" },
        { q: "'Provided' means?", a: ["Removed", "Destroyed", "Gave", "Took"], c: 2, exp: "Provided = gave / supplied.", tag: "RI.3.4" },
        { q: "READ: 'Maya heard thunder and grabbed her umbrella.' What can you infer?", a: ["Hot and sunny", "Cold and snowy", "About to rain", "Foggy"], c: 2, exp: "Thunder + umbrella → rain.", tag: "RL.3.1" },
        { q: "Which detail best supports the inference?", a: ["She heard thunder", "She left the door", "It was distant", "She moved quickly"], c: 0, exp: "Thunder is a direct weather clue.", tag: "RL.3.1" },
        { q: "READ: 'Frogs live in water AND on land. Tadpoles live only underwater until they grow legs.' How do tadpoles and adult frogs differ?", a: ["Tadpoles live on land", "Tadpoles have legs", "Tadpoles live only underwater", "Tadpoles are larger"], c: 2, exp: "Text directly contrasts their environments.", tag: "RI.3.9" },
        { q: "'Amphibians' most likely means?", a: ["Only swim", "Live in water and land", "Have no legs", "Cold-blooded reptiles only"], c: 1, exp: "The text defines it: water AND land.", tag: "RI.3.4" },
        { q: "How is the frog text organized?", a: ["Problem-solution", "Cause-effect", "Sequence", "Compare-contrast"], c: 1, exp: "Tadpoles grow legs (cause) → move to land (effect).", tag: "RI.3.8" },
        { q: "READ: 'Grandfather told stories every evening; children sat at his feet, hanging on every word.' Point of view?", a: ["First person", "Second person", "Third person", "No clear POV"], c: 2, exp: "'The children' and 'his' = third person.", tag: "RL.3.6" },
        { q: "'Hanging on every word' means?", a: ["Grabbing words", "Listening very carefully", "Falling asleep", "Repeating words"], c: 1, exp: "Idiom: paying very close attention.", tag: "RL.3.4" },
        { q: "Mood of the grandfather passage?", a: ["Scary", "Warm and peaceful", "Sad", "Frantic"], c: 1, exp: "Evening routine + widened eyes = cozy tradition.", tag: "RL.3.4" },
        { q: "POEM: 'The rain taps softly on my window, like fingers drumming a gentle song.' How does the poet feel?", a: ["Scared", "Bored", "Fascinated and peaceful", "Angry"], c: 2, exp: "Watching 'the whole morning long' shows fascination.", tag: "RL.3.5" },
        { q: "'Like fingers drumming' is an example of?", a: ["Rhyme", "Simile", "Alliteration", "Onomatopoeia"], c: 1, exp: "Comparison using 'like' = simile.", tag: "RL.3.4" },
        { q: "'Taps softly' suggests the rain is?", a: ["Loud", "Soft and quiet", "Musical", "Annoying"], c: 1, exp: "'Softly' directly tells us it is quiet.", tag: "RL.3.4" },
        { q: "What time of day does the speaker watch the rain?", a: ["Evening", "Afternoon", "Night", "Morning"], c: 3, exp: "'The whole morning long' is directly stated.", tag: "RL.3.1" },
        { q: "Best tool to find tadpoles in a science book?", a: ["Table of contents", "Glossary", "Index", "Caption"], c: 2, exp: "Index lists specific topics with page numbers.", tag: "RI.3.5" },
        { q: "READ: 'Edison failed 1,000 times before inventing the light bulb. He saw each failure as a way that didn't work.' Lesson?", a: ["Give up when hard", "Failure is part of success", "Only smart people invent", "Experiments aren't useful"], c: 1, exp: "Edison reframed failure as progress.", tag: "RL.3.2" },
        { q: "How did Edison VIEW his failures?", a: ["Embarrassed", "Gave up", "As learning steps", "Angry"], c: 2, exp: "He called them '1,000 ways that did not work.'", tag: "RI.3.3" },
        { q: "'Inventing' means?", a: ["Copying old things", "Creating something new", "Selling a product", "Breaking objects"], c: 1, exp: "Inventing = creating something new.", tag: "RI.3.4" },
        { q: "Best title for the Edison passage?", a: ["The Light Bulb", "Failure Is Not the End", "How Electricity Works", "Edison's Family"], c: 1, exp: "Main point is learning from failure.", tag: "RI.3.2" },
        { q: "Both grandfather and Edison share which theme?", a: ["Nature is powerful", "Stories matter", "Sharing knowledge matters", "Hard work pays off"], c: 2, exp: "Grandfather shared stories; Edison shared discovery.", tag: "RL.3.9" },
        { q: "Which sentence is an OPINION?", a: ["Edison failed 1,000 times", "He invented the light bulb", "He found 1,000 ways that didn't work", "Edison was the greatest inventor ever"], c: 3, exp: "'Greatest ever' is a judgment, not a fact.", tag: "RI.3.8" },
        { q: "Which text feature helps locate facts in a nonfiction book?", a: ["Illustrations", "Bold headings", "Rhyming verses", "Dialogue"], c: 1, exp: "Bold headings organize and guide readers to information.", tag: "RI.3.5" }
    ],
    set2: [
        { q: "NARRATIVE: 'Priya's stomach had butterflies before the race. Her legs felt like noodles.' 'Butterflies in stomach' means?", a: ["She was hungry", "She swallowed bugs", "She was nervous", "She was laughing"], c: 2, exp: "Common idiom for feeling nervous.", tag: "RL.3.4" },
        { q: "'Legs felt like noodles' suggests?", a: ["Tired from running", "Shaking and weak with nerves", "She liked noodles", "She fell down"], c: 1, exp: "Noodles = limp and unstable.", tag: "RL.3.4" },
        { q: "How does Priya feel at the starting line?", a: ["Excited and confident", "Nervous and uncertain", "Happy and relaxed", "Angry and ready"], c: 1, exp: "Butterflies + noodle legs signal nervousness.", tag: "RL.3.3" },
        { q: "What proves she prepared seriously?", a: ["She was at the line", "She had trained for months", "She felt butterflies", "Her legs were weak"], c: 1, exp: "'Trained for months' = serious preparation.", tag: "RL.3.1" },
        { q: "INFO: 'Wolves live in packs. The pack finds food and protects young.' Main idea?", a: ["Wolves are dangerous", "Wolves have sharp teeth", "Wolves are social animals that work as a team", "Wolves run fast"], c: 2, exp: "Pack, teamwork, roles = social cooperation.", tag: "RI.3.2" },
        { q: "Why do wolves live in packs?", a: ["To sleep together", "To find food and protect young", "To run faster", "To make loud sounds"], c: 1, exp: "Directly stated in the text.", tag: "RI.3.1" },
        { q: "'Role' most likely means?", a: ["A bread roll", "A job or function", "A game", "A sound"], c: 1, exp: "Each wolf has a role = a specific job.", tag: "RI.3.4" },
        { q: "Best source to learn more about wolf habitats?", a: ["A cookbook", "A science encyclopedia", "A poetry book", "A math textbook"], c: 1, exp: "Wolf habitats = science topic.", tag: "RI.3.5" },
        { q: "FABLE: 'A thirsty crow dropped pebbles into a pitcher until the water rose enough to drink.' Moral?", a: ["Never drink water", "Find another pitcher", "Use your brain to solve problems", "Ask for help"], c: 2, exp: "Crow used cleverness to overcome the challenge.", tag: "RL.3.2" },
        { q: "How did the crow solve the problem?", a: ["Broke the pitcher", "Asked another bird", "Dropped pebbles to raise water", "Flew to a river"], c: 2, exp: "Directly described in the fable.", tag: "RL.3.3" },
        { q: "Best character trait for the crow?", a: ["Lazy", "Clever and patient", "Greedy", "Cowardly"], c: 1, exp: "Added pebbles one by one = patient and clever.", tag: "RL.3.3" },
        { q: "This story is a FABLE because?", a: ["It has real animals", "It has a moral and is fiction", "It is very old", "It has pictures"], c: 1, exp: "Fables = fiction with a moral.", tag: "RL.3.5" },
        { q: "INFO: 'Children walk miles to school where there are no desks, yet they come because education can change their lives.' Author's purpose?", a: ["To entertain", "To inform and inspire", "To sell supplies", "To explain school construction"], c: 1, exp: "Facts + powerful message = inform and inspire.", tag: "RI.3.6" },
        { q: "What motivates students to attend school?", a: ["Food is served", "Parents force them", "Education can change their lives", "They enjoy walking"], c: 2, exp: "Directly stated in the last sentence.", tag: "RI.3.1" },
        { q: "Synonym for 'education'?", a: ["Ignorance", "Learning", "Forgetting", "Sleeping"], c: 1, exp: "Education = the process of learning.", tag: "L.3.4" },
        { q: "How does the school passage differ from the wolf passage?", a: ["It's about animals", "It includes a moral", "It talks about human choices", "It has figurative language"], c: 2, exp: "Wolf = animal behavior; School = human choices.", tag: "RI.3.9" },
        { q: "INFO: 'Volcanoes erupt, releasing lava that destroys AND creates new land.' One positive effect?", a: ["Causes destruction", "Creates new land", "Makes air dirty", "Kills animals"], c: 1, exp: "'Creates new land as it cools' = positive effect.", tag: "RI.3.3" },
        { q: "'Erupts' means?", a: ["Sleeps quietly", "Bursts open suddenly", "Melts slowly", "Freezes"], c: 1, exp: "Context: hot lava pours out = bursts open.", tag: "RI.3.4" },
        { q: "'Volcanoes are completely bad.' Is this supported by the text?", a: ["Yes, text says so", "No, lava creates new land", "Yes, lava is mentioned", "No, only oceans discussed"], c: 1, exp: "Text directly says lava creates new land.", tag: "RI.3.8" },
        { q: "Best source for a volcano research report?", a: ["Dragon story", "Science magazine about Earth", "Dictionary only", "Ocean book with no volcanoes"], c: 1, exp: "Science magazine covers Earth science topics.", tag: "RI.3.5" },
        { q: "Best outline headings for a volcano report?", a: ["Fun Facts / My Opinion", "What Are Volcanoes / How They Erupt / Effects", "Volcanoes vs Dragons", "Weather / Clouds / Rain"], c: 1, exp: "Three logical content headings organize the topic.", tag: "RI.3.5" },
        { q: "Theme appearing most across today's passages?", a: ["Animals are dangerous", "Understanding the world helps us grow", "Rain is beautiful", "Children dislike school"], c: 1, exp: "Edison, wolves, school, volcanoes: all expand knowledge.", tag: "RL.3.9" },
        { q: "Which detail about volcanoes is a FACT?", a: ["Volcanoes are terrifying", "Volcanoes are found on land or underwater", "Lava is the prettiest thing", "Volcanoes should be removed"], c: 1, exp: "'Found on land or underwater' is an observable fact.", tag: "RI.3.8" }
    ],
    set3: [
        { q: "POEM: 'The sun dipped low and painted the sky in shades of orange and pink.' This is an example of?", a: ["Simile", "Personification", "Rhyme", "Alliteration"], c: 1, exp: "Sun 'painted' = giving human action to sun = personification.", tag: "RL.3.4" },
        { q: "'Dipped low' suggests the sun is?", a: ["Rising", "Setting", "Hidden by clouds", "Very hot"], c: 1, exp: "Sun dipping low = sunset.", tag: "RL.3.4" },
        { q: "STORY: 'Zoe practiced piano every day for a year. At the recital, she played perfectly.' What theme fits best?", a: ["Music is boring", "Practice leads to success", "Recitals are stressful", "Piano is easy"], c: 1, exp: "A year of practice → perfect performance.", tag: "RL.3.2" },
        { q: "What character trait does Zoe show?", a: ["Lazy", "Dedicated", "Careless", "Jealous"], c: 1, exp: "Daily practice for a year = dedicated.", tag: "RL.3.3" },
        { q: "INFO: 'In winter, some animals migrate south for warmth. Others hibernate, sleeping through the cold months.' How are migration and hibernation SIMILAR?", a: ["Both happen in summer", "Both help animals survive winter", "Both involve flying", "Both are done by insects"], c: 1, exp: "Both are survival strategies for winter.", tag: "RI.3.9" },
        { q: "How do migration and hibernation DIFFER?", a: ["One is faster", "One involves moving, the other involves sleeping", "One happens in spring", "They don't differ"], c: 1, exp: "Migrate=travel; hibernate=sleep.", tag: "RI.3.9" },
        { q: "'Hibernate' most likely means?", a: ["To eat a lot", "To sleep through winter", "To fly south", "To grow thicker fur"], c: 1, exp: "Context: 'sleeping through the cold months.'", tag: "RI.3.4" },
        { q: "Cause: an animal lives where winters are harsh. Effect?", a: ["It sleeps through summer", "It migrates or hibernates", "It grows bigger", "It moves to the city"], c: 1, exp: "Harsh winters cause animals to adapt (migrate/hibernate).", tag: "RI.3.3" },
        { q: "NARRATIVE: 'When Eli won the spelling bee, he didn't cheer loudly. He just smiled quietly and thought of all the late nights studying.' What does this show?", a: ["Eli was unhappy", "Eli was humble and hardworking", "Eli forgot he had studied", "Eli wanted more prizes"], c: 1, exp: "Quiet pride + remembering hard work = humble.", tag: "RL.3.3" },
        { q: "The author includes 'late nights studying' to show?", a: ["Eli was tired", "The prize is small", "His success came from real effort", "The bee lasted all night"], c: 2, exp: "Late nights = the effort behind the win.", tag: "RL.3.1" },
        { q: "What is the SETTING of the spelling bee story?", a: ["A library", "A competition stage", "A classroom", "Eli's home"], c: 1, exp: "A spelling bee takes place on a competition stage.", tag: "RL.3.3" },
        { q: "INFO: 'The Amazon River is the largest river by volume in the world and flows through the rainforest.' What is stated as a FACT?", a: ["Amazon is the most beautiful", "Amazon flows through the rainforest", "Rainforests are dangerous", "Rivers are better than oceans"], c: 1, exp: "Volume claim and location are measurable facts.", tag: "RI.3.8" },
        { q: "A student wants to know how long the Amazon River is. Best source?", a: ["A story about a boy on a raft", "An atlas or geography textbook", "A poem about rivers", "A cookbook"], c: 1, exp: "Atlas = reference with geographic data.", tag: "RI.3.5" },
        { q: "The word 'volume' in 'largest by volume' means?", a: ["Loudness", "Amount of water", "Number of fish", "Width"], c: 1, exp: "River volume = amount of water flowing.", tag: "RI.3.4" },
        { q: "POEM: 'I am the wind. I push the waves, / Rattle the leaves, and fill the sails.' This is written in?", a: ["Third person", "First person", "Second person", "No clear person"], c: 1, exp: "'I am the wind' = first person.", tag: "RL.3.6" },
        { q: "'Fill the sails' tells us the wind is?", a: ["Weak", "Powerful", "Cold", "Silent"], c: 1, exp: "Filling sails requires strong force.", tag: "RL.3.4" },
        { q: "What literary device is used in the wind poem?", a: ["Wind talking = simile", "Wind talking = personification", "Wind talking = rhyme", "Wind talking = alliteration"], c: 1, exp: "Wind speaks as 'I' = personification.", tag: "RL.3.4" },
        { q: "The animal adaptation passage BEST fits which text structure?", a: ["Narrative", "Compare and contrast", "Problem-solution", "Chronological order"], c: 1, exp: "Compares migration vs hibernation.", tag: "RI.3.8" },
        { q: "Which would be a GOOD introduction sentence for a report about rainforests?", a: ["I like trees.", "Rainforests cover about 6% of Earth's surface and contain over half of all species.", "Trees are big.", "The Amazon is wet."], c: 1, exp: "Strong intro = specific, informative, engaging.", tag: "W.3.2" },
        { q: "Zoe (piano) and Eli (spelling bee) share which trait?", a: ["Musical talent", "They both won easily", "Hard work and dedication", "They disliked competition"], c: 2, exp: "Both practiced hard → succeeded.", tag: "RL.3.9" },
        { q: "Which passage used CAUSE AND EFFECT text structure?", a: ["Zoe's piano story", "The wind poem", "Animal adaptations passage", "Eli's spelling bee story"], c: 2, exp: "Cause (harsh winter) → effect (hibernate/migrate).", tag: "RI.3.8" },
        { q: "'Rattle the leaves' in the wind poem uses which sound device?", a: ["Simile", "Metaphor", "Onomatopoeia", "Personification"], c: 2, exp: "'Rattle' sounds like what it describes = onomatopoeia.", tag: "RL.3.4" },
        { q: "The BEST summary of the animal adaptation passage is?", a: ["Animals have fun in winter", "Some animals migrate and others hibernate to survive winter", "Animals eat more in winter", "Winter is cold for everyone"], c: 1, exp: "Covers both strategies and their shared purpose.", tag: "RI.3.2" }
    ],
    set4: [
        { q: "INFO: 'Honeybees live in colonies of up to 80,000 bees. Each bee has a job: queen, worker, or drone.' How is the colony organized?", a: ["By size", "By age", "By job roles", "By color"], c: 2, exp: "Text states three distinct roles.", tag: "RI.3.3" },
        { q: "The queen's job is MOST LIKELY?", a: ["Make honey", "Lay eggs to grow the colony", "Guard the hive", "Dance to find flowers"], c: 1, exp: "In bee colonies, the queen lays eggs.", tag: "RI.3.1" },
        { q: "'Colony' most likely means?", a: ["A type of flower", "A large organized group", "A single bee", "A beehive shape"], c: 1, exp: "Context: 80,000 bees living together = colony.", tag: "RI.3.4" },
        { q: "STORY: 'The old lighthouse stood at the edge of the cliff, its light sweeping the dark ocean like a slow, patient eye.' 'Slow, patient eye' is a?", a: ["Simile", "Metaphor", "Personification", "Onomatopoeia"], c: 1, exp: "Light compared to an eye WITHOUT 'like/as' = metaphor.", tag: "RL.3.4" },
        { q: "What does the lighthouse do in the story?", a: ["Swims in the ocean", "Guides ships with its light", "Grows on the cliff", "Watches birds"], c: 1, exp: "'Sweeping the dark ocean' = guiding ships.", tag: "RL.3.1" },
        { q: "The mood of the lighthouse passage is?", a: ["Playful", "Mysterious and calm", "Angry", "Funny"], c: 1, exp: "Dark ocean, patient light = mysterious calm.", tag: "RL.3.4" },
        { q: "COMPARE: Bees and wolves both?", a: ["Make honey", "Fly", "Live in organized groups with roles", "Hunt alone"], c: 2, exp: "Both live in groups where members have specific roles.", tag: "RI.3.9" },
        { q: "INFO: 'Plastic waste in oceans harms sea turtles, who mistake bags for jellyfish.' What problem does the text describe?", a: ["Turtles eat too much", "Plastic pollution harms sea life", "Jellyfish are dangerous", "Oceans are too deep"], c: 1, exp: "Plastic mistaken for food = the harm.", tag: "RI.3.3" },
        { q: "What would be the best SOLUTION based on the text?", a: ["Feed turtles more", "Remove plastic waste from oceans", "Teach turtles to avoid bags", "Build more hives"], c: 1, exp: "The problem (plastic) → solution (remove plastic).", tag: "RI.3.3" },
        { q: "'Mistake bags for jellyfish' means turtles?", a: ["Think bags are toys", "Cannot see well", "Confuse the two things", "Are very hungry"], c: 2, exp: "Mistake for = confuse with.", tag: "RI.3.4" },
        { q: "NARRATIVE: 'Leo froze when he saw the stage full of people. His mouth went dry. Then he remembered Grandma's words: You are ready.' What changed Leo's mind?", a: ["He ran away", "He remembered encouraging words", "He forgot his speech", "He closed his eyes"], c: 1, exp: "Grandma's encouraging words changed his state of mind.", tag: "RL.3.3" },
        { q: "'His mouth went dry' is an example of?", a: ["Simile", "Metaphor", "Idiom showing nervousness", "Onomatopoeia"], c: 2, exp: "Dry mouth = physical sign of nervous feeling = idiom.", tag: "RL.3.4" },
        { q: "What is the theme of Leo's story?", a: ["Stage fright is permanent", "Encouragement helps you face your fears", "Grandmas are always right", "Speeches are boring"], c: 1, exp: "Grandma's words helped Leo overcome fear.", tag: "RL.3.2" },
        { q: "INFO text structures – which word signals CAUSE AND EFFECT?", a: ["Meanwhile", "However", "Therefore", "Although"], c: 2, exp: "'Therefore' introduces a result/effect.", tag: "RI.3.8" },
        { q: "In a story, what does 'rising action' mean?", a: ["Characters fly up", "Events build toward the climax", "The story ends", "The setting changes"], c: 1, exp: "Rising action = events that build toward the climax.", tag: "RL.3.5" },
        { q: "Which heading best organizes a report about ocean pollution?", a: ["Fun Ocean Facts / Sea Creatures / My Opinion", "Causes of Pollution / Effects on Animals / Solutions", "What I Think / What Others Think", "Fish / Whales / Sharks"], c: 1, exp: "Logical, factual structure for a nonfiction report.", tag: "W.3.2" },
        { q: "The lighthouse passage is FICTION because?", a: ["It mentions the ocean", "It describes feelings and uses figurative language", "It is very short", "It has a lighthouse"], c: 1, exp: "Figurative language + narrative voice = fiction.", tag: "RL.3.5" },
        { q: "POEM: 'Autumn leaves spiral down / Like tiny spinning tops in town.' What does 'spiral' suggest?", a: ["Leaves fall straight down", "Leaves twirl as they fall", "Leaves are red", "Leaves make noise"], c: 1, exp: "Spiral = twisting motion.", tag: "RL.3.4" },
        { q: "'Like tiny spinning tops' is a?", a: ["Metaphor", "Simile", "Personification", "Rhyme"], c: 1, exp: "Comparison using 'like' = simile.", tag: "RL.3.4" },
        { q: "Which sentence best SUMMARIZES the bee colony passage?", a: ["Bees make honey and sting people", "Honeybee colonies are large, organized groups where every bee has a role", "Bees live outside", "Drones are the most important bees"], c: 1, exp: "Covers colony size, organization, and roles.", tag: "RI.3.2" },
        { q: "Leo (stage fright), Priya (race), and Zoe (piano) all share?", a: ["Musical talent", "Nervousness that they overcome through effort", "They all lose", "They stop trying"], c: 1, exp: "All face a challenge and work through it.", tag: "RL.3.9" },
        { q: "Which text type uses STANZAS and LINE BREAKS?", a: ["Informational article", "Fiction story", "Poem", "Nonfiction report"], c: 2, exp: "Stanzas and line breaks are features of poetry.", tag: "RL.3.5" },
        { q: "A student writes: 'Plastic bags are ugly.' Is this fact or opinion?", a: ["Fact", "Opinion", "Both", "Neither"], c: 1, exp: "'Ugly' is a personal judgment = opinion.", tag: "RI.3.8" }
    ],
    set5: [
        { q: "INFO: 'The Great Wall of China stretches over 13,000 miles. It was built to protect China from invasion.' Why was the wall built?", a: ["For tourism", "To protect China from invasion", "As a running track", "To hold water"], c: 1, exp: "Directly stated: protect from invasion.", tag: "RI.3.1" },
        { q: "'Stretches' in context means?", a: ["Becomes elastic", "Extends across a great distance", "Gets taller", "Shrinks"], c: 1, exp: "Context: 13,000 miles long = extends/spans.", tag: "RI.3.4" },
        { q: "'Invasion' means?", a: ["A loud sound", "A celebration", "An attack by outside forces", "A long journey"], c: 2, exp: "Invasion = military attack from outside.", tag: "RI.3.4" },
        { q: "STORY: 'The river was higher than Ana had ever seen it. She gripped the edge of the kayak and paddled hard.' How does Ana feel?", a: ["Bored", "Nervous but determined", "Happy and relaxed", "Confused"], c: 1, exp: "Gripping + high water = nervous; paddling hard = determined.", tag: "RL.3.3" },
        { q: "What does 'gripped the edge' tell you?", a: ["She was tired", "She showed tension and effort", "She was about to fall", "She was waving"], c: 1, exp: "Gripping = physical sign of tension/focus.", tag: "RL.3.4" },
        { q: "COMPARE: Great Wall and Ana's kayak story both involve?", a: ["Water", "Overcoming a significant challenge", "China", "Building something"], c: 1, exp: "Wall: built to stop invasion (challenge); Ana: navigates dangerous river (challenge).", tag: "RL.3.9" },
        { q: "INFO: 'The sun is a star, not a planet. It is so large that about 1 million Earths could fit inside it.' The author's purpose?", a: ["To entertain", "To persuade", "To inform with factual data", "To describe feelings"], c: 2, exp: "Factual statements about size and classification = inform.", tag: "RI.3.6" },
        { q: "'About 1 million Earths' is used to?", a: ["Scare the reader", "Help the reader visualize the sun's size", "Describe the planet", "Show the sun is dangerous"], c: 1, exp: "Comparing to known thing (Earth) = helps visualize size.", tag: "RI.3.6" },
        { q: "NARRATIVE: 'The cat sat perfectly still, watching the bird feeder. Then, in a flash, she leaped.' What can you INFER the cat will do next?", a: ["Fall asleep", "Run away", "Try to catch a bird", "Eat from the feeder"], c: 2, exp: "Still → watching → sudden leap = hunting behavior.", tag: "RL.3.1" },
        { q: "The word 'flash' in the story creates a sense of?", a: ["Slowness", "Sadness", "Speed", "Darkness"], c: 2, exp: "'In a flash' = suddenly and quickly.", tag: "RL.3.4" },
        { q: "POEM: 'Stars are scattered diamonds on velvet skies.' This is a?", a: ["Simile", "Metaphor", "Onomatopoeia", "Personification"], c: 1, exp: "Stars ARE diamonds (no like/as) = metaphor.", tag: "RL.3.4" },
        { q: "The poem suggests the poet feels?", a: ["Bored by stars", "Amazed by the beauty of the night sky", "Afraid of the dark", "Curious about diamonds"], c: 1, exp: "Diamonds on velvet = luxurious, beautiful image.", tag: "RL.3.5" },
        { q: "INFO: 'Exercise strengthens muscles and improves mood. Even a 20-minute walk can make a difference.' Main idea?", a: ["Walking is the only exercise", "Exercise has clear physical and mental benefits", "You must exercise for hours", "Mood is not important"], c: 1, exp: "Both muscles (physical) and mood (mental) = two benefits.", tag: "RI.3.2" },
        { q: "'Strengthens' means?", a: ["Weakens", "Makes stronger", "Makes shorter", "Removes"], c: 1, exp: "Strengthen = make stronger.", tag: "RI.3.4" },
        { q: "A student wants to compare this exercise passage with another health article. Best tool?", a: ["A thesaurus", "Two nonfiction health texts", "A fiction story", "A poem"], c: 1, exp: "Two nonfiction texts allow direct comparison of information.", tag: "RI.3.9" },
        { q: "Which summary BEST captures the exercise passage?", a: ["Exercise is hard work", "A brief walk can improve muscles and mood", "You need a gym", "Exercise is only for athletes"], c: 1, exp: "Covers physical and mental benefit from even short activity.", tag: "RI.3.2" },
        { q: "Ana's kayak story and the cat-at-the-feeder story both use which technique?", a: ["Dialogue", "Poems with rhyme", "Action verbs to show tension", "Lists of facts"], c: 2, exp: "'Gripped,' 'paddled,' 'leaped' = action verbs for tension.", tag: "RL.3.4" },
        { q: "INFO: 'Renewable energy, like wind and solar power, does not run out unlike fossil fuels.' Renewable energy is DIFFERENT from fossil fuels because?", a: ["It is more expensive", "It does not run out", "It is older", "It is only used at night"], c: 1, exp: "Directly contrasted: renewable = does not run out.", tag: "RI.3.9" },
        { q: "'Unlike' in the passage signals?", a: ["Similarity", "Contrast", "Addition", "Sequence"], c: 1, exp: "'Unlike' = a comparison showing difference.", tag: "RI.3.8" },
        { q: "Which BEST describes 'renewable'?", a: ["Used once and gone", "Can be used again and again", "Very expensive", "Made from coal"], c: 1, exp: "Renewable = can be replenished / does not run out.", tag: "RI.3.4" },
        { q: "The Great Wall passage and the sun passage are BOTH?", a: ["Fiction stories", "Informational texts with factual details", "Poems", "Personal narratives"], c: 1, exp: "Both use facts and data to inform the reader.", tag: "RI.3.5" },
        { q: "STORY ELEMENT: Ana's kayaking story lacks which element that would make it feel complete?", a: ["A setting", "A character", "A resolution/ending", "A problem"], c: 2, exp: "We know the problem (high river) but not how it resolves.", tag: "RL.3.5" },
        { q: "'Even a 20-minute walk can make a difference.' This supports which claim?", a: ["Long exercise is needed", "Small efforts can have real benefits", "Walking is not real exercise", "Only running works"], c: 1, exp: "Even a SHORT walk helps = small effort, real result.", tag: "RI.3.8" }
    ],
    set6: [
        { q: "INFO: 'Mount Everest is 29,032 feet tall—the highest point on Earth. Thousands have tried to reach its summit.' 'Summit' means?", a: ["Base camp", "The very top", "A path on the side", "The mountain's name"], c: 1, exp: "Summit = the highest point of a mountain.", tag: "RI.3.4" },
        { q: "The author includes the height to?", a: ["Confuse the reader", "Prove the challenge is enormous", "Show it is small", "Compare it to volcanoes"], c: 1, exp: "29,032 feet emphasizes how extraordinarily tall it is.", tag: "RI.3.6" },
        { q: "Which text feature would BEST appear in an Everest article?", a: ["Stanza breaks", "A diagram showing elevation by zone", "Rhyming lines", "A recipe"], c: 1, exp: "A diagram shows technical height data visually.", tag: "RI.3.5" },
        { q: "NARRATIVE: 'Despite losing the first two games, the soccer team cheered each other on. By game five, they won the championship.' Theme?", a: ["Soccer is easy", "Teamwork and resilience lead to success", "Championships are rare", "Losing always leads to winning"], c: 1, exp: "Support through losses → final victory = resilience + team.", tag: "RL.3.2" },
        { q: "What does 'despite' signal in the sentence?", a: ["In addition to", "Because of", "Even though", "Only if"], c: 2, exp: "'Despite' = even though / in contrast to.", tag: "L.3.4" },
        { q: "Which word best describes the team's attitude?", a: ["Defeated", "Resilient and encouraging", "Angry", "Divided"], c: 1, exp: "Cheering each other on through losses = resilient.", tag: "RL.3.3" },
        { q: "INFO: 'Water can exist as a solid (ice), liquid (water), or gas (steam).' This is an example of which text structure?", a: ["Narrative", "Cause-effect", "Classification/Description", "Compare-contrast"], c: 2, exp: "Lists three states and labels them = classify/describe.", tag: "RI.3.8" },
        { q: "What causes water to become steam?", a: ["Cooling down", "Adding salt", "Heating to boiling", "Freezing"], c: 2, exp: "Steam = water heated past boiling point.", tag: "RI.3.3" },
        { q: "POEM: 'The mountain does not hurry, / Yet it reaches the sky.' What does the poem suggest?", a: ["Mountains are lazy", "Patience and persistence achieve great things", "Mountains should move faster", "The sky is very close"], c: 1, exp: "No hurry + reaches sky = slow and steady wins.", tag: "RL.3.2" },
        { q: "'Reaches the sky' is best described as?", a: ["Literal fact", "Simile", "Hyperbole / exaggeration for effect", "Personification"], c: 2, exp: "Mountains don't literally touch the sky = exaggeration (hyperbole).", tag: "RL.3.4" },
        { q: "The mountain poem and the soccer team story share what theme?", a: ["Sports are hard", "Nature is powerful", "Patient persistence leads to achievement", "Mountains are taller than people"], c: 2, exp: "Mountain: slow/steady; Soccer team: keeps going through losses.", tag: "RL.3.9" },
        { q: "INFO: 'Trees absorb carbon dioxide and release oxygen. Cutting too many trees raises CO2 levels.' Cutting trees causes?", a: ["More oxygen", "Lower CO2", "Higher CO2 levels", "More shade"], c: 2, exp: "Fewer trees = less CO2 absorbed = higher CO2 levels.", tag: "RI.3.3" },
        { q: "The BEST title for that tree passage?", a: ["My Favorite Tree", "How Trees Keep Our Air Clean", "Cutting Wood for Furniture", "Trees Are Tall"], c: 1, exp: "Covers both absorption function and impact of cutting.", tag: "RI.3.2" },
        { q: "'Absorb' means?", a: ["Release", "Push away", "Take in / soak up", "Grow"], c: 2, exp: "Absorb = take in (trees take in CO2).", tag: "RI.3.4" },
        { q: "NARRATIVE: 'The empty page scared Jamie more than anything. But then one word appeared, then another, and soon a story grew like a garden.' What does the metaphor 'story grew like a garden' suggest?", a: ["Stories are planted in soil", "Writing takes time and slowly flourishes", "Gardens write stories", "Jamie liked gardening"], c: 1, exp: "Garden grows slowly from seeds = story develops gradually. Note: 'like' makes it a simile.", tag: "RL.3.4" },
        { q: "What scared Jamie at first?", a: ["A spider", "Starting to write on a blank page", "Losing a pet", "Loud thunder"], c: 1, exp: "'Empty page scared Jamie' = starting to write.", tag: "RL.3.3" },
        { q: "The theme of Jamie's writing story most closely matches which other character?", a: ["The thirsty crow (set 2)", "Eli at the spelling bee (set 3)", "Ana in the kayak (set 5)", "The cat at the feeder (set 5)"], c: 1, exp: "Both Jamie and Eli faced a scary start then persevered.", tag: "RL.3.9" },
        { q: "Which passage would BEST compare with the tree/CO2 passage for a research project on climate?", a: ["A poem about autumn leaves", "An article about renewable energy", "A narrative about camping", "A story about a snowman"], c: 1, exp: "Renewable energy also addresses environmental impact.", tag: "RI.3.9" },
        { q: "In an informational essay, a CONCLUSION should?", a: ["Introduce new facts", "Restate the main idea and leave the reader thinking", "List only names", "Be longer than the introduction"], c: 1, exp: "Good conclusions summarize and leave impression.", tag: "W.3.2" },
        { q: "Jamie's story uses which literary technique?", a: ["Multiple points of view", "Metaphor and personification", "Scientific data", "A table of contents"], c: 1, exp: "'Story grew like a garden' = figurative language (simile/metaphor).", tag: "RL.3.4" },
        { q: "Which statement BEST reflects the Everest passage?", a: ["Anyone can climb Everest easily", "Everest represents one of Earth's greatest physical challenges", "Everest is only famous for its snow", "Climbers go there every day"], c: 1, exp: "Height + 'thousands have tried' = enormous challenge.", tag: "RI.3.8" },
        { q: "Across all 6 ELA sets, which theme appears MOST often?", a: ["Animals are dangerous", "Persistence and effort matter in facing challenges", "Nature is always described with similes", "Families are always the solution"], c: 1, exp: "Edison, Leo, Priya, Zoe, Eli, Ana, soccer team: all persist through a challenge.", tag: "RL.3.9" },
        { q: "A student writes a report comparing trees and renewable energy. Which structure is BEST?", a: ["Two separate unrelated paragraphs", "An introduction, compare-contrast body, and conclusion", "A poem", "A list of their opinions"], c: 1, exp: "Intro + organized comparison + conclusion = proper report structure.", tag: "W.3.2" }
    ]
};

const chineseDB = {
    set1: [
        { q: "拼音：'苹果'的正确拼音？", a: ["píng gǔo", "píng guǒ", "pīng guǒ", "pīng gǔo"], c: 1, exp: "苹果 = píng guǒ（第二声+第三声）。", tag: "拼音" },
        { q: "量词：一___书", a: ["个", "只", "本", "条"], c: 2, exp: "书的量词是'本'。", tag: "量词" },
        { q: "'森林'是什么意思？", a: ["Forest", "Mountain", "Ocean", "Desert"], c: 0, exp: "森林 = Forest（树木茂盛的地方）。", tag: "识字" },
        { q: "'快'的反义词？", a: ["跑", "慢", "高", "大"], c: 1, exp: "快慢相对。", tag: "反义词" },
        { q: "选出正确句子：", a: ["我吃饭喜欢", "喜欢我饭吃", "我喜欢吃饭", "饭吃我喜欢"], c: 2, exp: "中文语序：主语+谓语+宾语。", tag: "句法" }
    ],
    set2: [
        { q: "'日'代表什么？", a: ["Moon", "Sun", "Star", "Cloud"], c: 1, exp: "日是太阳的象形字。", tag: "识字" },
        { q: "填空：他___吃苹果。（表示喜欢）", a: ["不", "很", "喜欢", "难"], c: 2, exp: "喜欢 = to like.", tag: "词汇" },
        { q: "'八十五'用阿拉伯数字写是？", a: ["58", "85", "805", "850"], c: 1, exp: "八十五 = 80+5 = 85。", tag: "数字" },
        { q: "'明天'是什么意思？", a: ["Yesterday", "Today", "Tomorrow", "Morning"], c: 2, exp: "明天 = Tomorrow。", tag: "词汇" },
        { q: "她___画画。（能力）", a: ["不", "要", "会", "的"], c: 2, exp: "'会'表示有能力做某事。", tag: "语法" }
    ],
    set3: [
        { q: "正确语序：①画画 ②喜欢 ③我", a: ["①②③", "③②①", "②③①", "③①②"], c: 1, exp: "我（主）喜欢（谓）画画（宾）= ③②①。", tag: "句法" },
        { q: "'河、海、湖'共同的偏旁是？", a: ["木字旁", "三点水", "口字旁", "草字头"], c: 1, exp: "三点水（氵）都与水有关。", tag: "部首" },
        { q: "'大'字加一笔可变成？", a: ["天", "太", "火", "木"], c: 1, exp: "大字下面加一点变成'太'。", tag: "构字" },
        { q: "'床前明月光，疑是地上霜'主题是？", a: ["想吃东西", "思念家乡", "描写动物", "写春天"], c: 1, exp: "李白《静夜思》，月光引发思乡之情。", tag: "古诗" },
        { q: "描写天气的词语是？", a: ["高兴", "晴天", "美丽", "聪明"], c: 1, exp: "晴天 = sunny day，是天气词。", tag: "词汇分类" }
    ]
};

// Merge into global DB object (referenced by app.js)
const DB = {
    math: mathDB,
    ela: elaDB,
    chinese: chineseDB
};
